/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef sPutString_TECSGEN_H
#define sPutString_TECSGEN_H

/*
 * signature   :  sPutString
 * global name :  sPutString
 * context     :  task
 */

#ifndef TOPPERS_MACRO_ONLY

/* signature descriptor #_SD_# */
struct tag_sPutString_VDES {
    struct tag_sPutString_VMT *VMT;
};

/* signature function table #_SFT_# */
struct tag_sPutString_VMT {
    void           (*putString__T)( const struct tag_sPutString_VDES *edp, const char_t* string );
};

/* signature descriptor #_SDES_# for dynamic join */
#ifndef Descriptor_of_sPutString_Defined
#define  Descriptor_of_sPutString_Defined
typedef struct { struct tag_sPutString_VDES *vdes; } Descriptor( sPutString );
#endif
#endif /* TOPPERS_MACRO_ONLY */

/* function id */
#define	FUNCID_SPUTSTRING_PUTSTRING            (1)

#endif /* sPutString_TECSGEN_H */
