/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCt2_tecsgen.h"
#include "tCt2_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
/* cell: ct2_CB:  ct2 id=3 */
tCt2_CB ct2_CB = {
    /* call port (CB_ALL) #_CP_# */ 
    /* attribute */ 
    20,                                      /* a */
    /* var */ 
    31,                                      /* v */
};

/* entry port descriptor #_EPD_# */
/* ID to CB table #_CBTAB_# */
tCt2_CB *const tCt2_CB_ptab[] ={
    &ct2_CB,
};
