/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCt_no_CB_no_INIB_tecsgen.h"
#include "tCt_no_CB_no_INIB_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
int8_t Ct_no_CB_no_INIB_CB_buf_INIT[1];
/* cell CB #_CB_# */
/* cell: Ct_no_CB_no_INIB_CB:  Ct_no_CB_no_INIB id=16 */
tCt_no_CB_no_INIB_CB Ct_no_CB_no_INIB_CB = {
    /* attribute */ 
    Ct_no_CB_no_INIB_CB_buf_INIT,            /* buf */
};

/* entry port descriptor #_EPD_# */
/* ID to CB table #_CBTAB_# */
tCt_no_CB_no_INIB_CB *const tCt_no_CB_no_INIB_CB_ptab[] ={
    &Ct_no_CB_no_INIB_CB,
};
