/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tSCt_no_CB_no_INIB_tecsgen.h"
#include "tSCt_no_CB_no_INIB_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
int8_t tSCt_no_CB_no_INIB_SINGLE_CELL_CB_buf_INIT[1];
/* cell CB #_CB_# */
struct tag_tSCt_no_CB_no_INIB_CB tSCt_no_CB_no_INIB_SINGLE_CELL_CB = 
{
    /* attribute */ 
    tSCt_no_CB_no_INIB_SINGLE_CELL_CB_buf_INIT, /* buf */
};

/* entry port descriptor #_EPD_# */
