/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef GLOBAL_TECSGEN_H
#define GLOBAL_TECSGEN_H


/* header imported by import_C #_IMP_# */
#include "cygwin_tecs.h"
#include "t_stddef.h"
#include "t_syslog.h"
/**/

#ifndef TOPPERS_MACRO_ONLY

 extern void tTask_CB_initialize();
 extern void tPutStringStdio_CB_initialize();
 extern void tHelloWorld_CB_initialize();
 extern void tTaskMain_CB_initialize();
 extern void nTECSInfo_tTECSInfo_CB_initialize();
 extern void nTECSInfo_tTECSInfoSub_CB_initialize();
 extern void nTECSInfo_tNamespaceInfo_CB_initialize();
 extern void nTECSInfo_tSignatureInfo_CB_initialize();
 extern void nTECSInfo_tFunctionInfo_CB_initialize();
 extern void nTECSInfo_tParamInfo_CB_initialize();
 extern void nTECSInfo_tCelltypeInfo_CB_initialize();
 extern void nTECSInfo_tCallInfo_CB_initialize();
 extern void nTECSInfo_tEntryInfo_CB_initialize();
 extern void nTECSInfo_tVarDeclInfo_CB_initialize();
 extern void nTECSInfo_tRegionInfo_CB_initialize();
 extern void nTECSInfo_tCellInfo_CB_initialize();
 extern void nTECSInfo_tRawEntryDescriptorInfo_CB_initialize();
 extern void nTECSInfo_tVoidTypeInfo_CB_initialize();
 extern void nTECSInfo_tBoolTypeInfo_CB_initialize();
 extern void nTECSInfo_tIntTypeInfo_CB_initialize();
 extern void nTECSInfo_tStructTypeInfo_CB_initialize();
 extern void nTECSInfo_tPtrTypeInfo_CB_initialize();
 extern void nTECSInfo_tDefinedTypeInfo_CB_initialize();
 extern void nTECSInfo_tDescriptorTypeInfo_CB_initialize();
 extern void nTECSInfo_tTECSInfoAccessor_CB_initialize();

#define INITIALIZE_TECS() \
 	tTask_CB_initialize();\
 	tPutStringStdio_CB_initialize();\
 	tHelloWorld_CB_initialize();\
 	tTaskMain_CB_initialize();\
 	nTECSInfo_tTECSInfo_CB_initialize();\
 	nTECSInfo_tTECSInfoSub_CB_initialize();\
 	nTECSInfo_tNamespaceInfo_CB_initialize();\
 	nTECSInfo_tSignatureInfo_CB_initialize();\
 	nTECSInfo_tFunctionInfo_CB_initialize();\
 	nTECSInfo_tParamInfo_CB_initialize();\
 	nTECSInfo_tCelltypeInfo_CB_initialize();\
 	nTECSInfo_tCallInfo_CB_initialize();\
 	nTECSInfo_tEntryInfo_CB_initialize();\
 	nTECSInfo_tVarDeclInfo_CB_initialize();\
 	nTECSInfo_tRegionInfo_CB_initialize();\
 	nTECSInfo_tCellInfo_CB_initialize();\
 	nTECSInfo_tRawEntryDescriptorInfo_CB_initialize();\
 	nTECSInfo_tVoidTypeInfo_CB_initialize();\
 	nTECSInfo_tBoolTypeInfo_CB_initialize();\
 	nTECSInfo_tIntTypeInfo_CB_initialize();\
 	nTECSInfo_tStructTypeInfo_CB_initialize();\
 	nTECSInfo_tPtrTypeInfo_CB_initialize();\
 	nTECSInfo_tDefinedTypeInfo_CB_initialize();\
 	nTECSInfo_tDescriptorTypeInfo_CB_initialize();\
 	nTECSInfo_tTECSInfoAccessor_CB_initialize();\
/* INITIALIZE_TECS terminator */

#define INITIALZE_TECSGEN() INITIALIZE_TECS()  /* for backward compatibility */

/* Descriptor for dynamic join */
#define Descriptor( signature_global_name )  DynDesc__ ## signature_global_name
#define is_descriptor_unjoined( desc )  ((desc).vdes==NULL)

#endif /* TOPPERS_MACRO_ONLY */

#define TASK_STATE_0   ((const int)0)
#define TASK_STATE_1   ((const int)1)
#define TECSTypeKind_BoolType ((const int8_t)1)
#define TECSTypeKind_IntType ((const int8_t)2)
#define TECSTypeKind_FloatType ((const int8_t)3)
#define TECSTypeKind_PtrType ((const int8_t)4)
#define TECSTypeKind_ArrayType ((const int8_t)5)
#define TECSTypeKind_DefinedType ((const int8_t)6)
#define TECSTypeKind_StructType ((const int8_t)7)
#define TECSTypeKind_EnumType ((const int8_t)8)
#define TECSTypeKind_VoidType ((const int8_t)9)
#define TECSTypeKind_DescriptorType ((const int8_t)10)
#define TECSTypeKind_FuncType ((const int8_t)11)
#define PARAM_DIR_IN   ((const int8_t)1)
#define PARAM_DIR_OUT  ((const int8_t)2)
#define PARAM_DIR_INOUT ((const int8_t)3)
#define PARAM_DIR_SEND ((const int8_t)4)
#define PARAM_DIR_RECEIVE ((const int8_t)5)
#define DECLTYPE_STMEMBER ((const int8_t)1)
#define DECLTYPE_ATTR  ((const int8_t)2)
#define DECLTYPE_VAR   ((const int8_t)3)
#define VARDECL_PLACE_STRUCT ((const int8_t)1)
#define VARDECL_PLACE_NON ((const int8_t)2)
#define VARDECL_PLACE_CB ((const int8_t)3)
#define VARDECL_PLACE_INIB ((const int8_t)4)
#define CALL_PLACE_NON ((const int8_t)1)
#define CALL_PLACE_INIB_DES ((const int8_t)2)
#define CALL_PLACE_CB_DES ((const int8_t)3)
#define CALL_PLACE_INIB_IDX ((const int8_t)4)
#define CALL_PLACE_CB_IDX ((const int8_t)5)
#define setRawEntryDescriptor( callDesc, callPortSignature, rawEntryDesc )   (callDesc).vdes = (struct tag_ ## callPortSignature ## _VDES *) rawEntryDesc

#endif /* GLOBAL_TECSGEN_H */
