/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "nTECSInfo_tTECSInfoAccessor_tecsgen.h"
#include "nTECSInfo_tTECSInfoAccessor_factory.h"

/* entry port descriptor type #_EDT_# */
/* eSelector */
struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES {
    const struct tag_nTECSInfo_sAccessor_VMT *vmt;
    tTECSInfoAccessor_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eSelector */
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectNamespaceInfoByName_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, const char_t* namespacePath)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectNamespaceInfoByName( lepd->idx, namespacePath );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfoByName_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, const char_t* celltypePath)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfoByName( lepd->idx, celltypePath );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureInfoByName_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, const char_t* signaturePath)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureInfoByName( lepd->idx, signaturePath );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectRegionInfoByName_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, const char_t* regionPath)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectRegionInfoByName( lepd->idx, regionPath );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectCellInfoByName_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, const char_t* cellPath)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectCellInfoByName( lepd->idx, cellPath );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSignatureNameOfCellEntry_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, const char_t* cellEntryPath, char_t* signatureGlobalName, int_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSignatureNameOfCellEntry( lepd->idx, cellEntryPath, signatureGlobalName, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedNamespaceInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* num_namespace, int_t* num_celltype, int_t* num_signature)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedNamespaceInfo( lepd->idx, name, max_len, num_namespace, num_celltype, num_signature );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectNamespaceInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectNamespaceInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCelltypeInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* num_attr, int_t* num_var, int_t* num_call, int_t* num_entry)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCelltypeInfo( lepd->idx, name, max_len, num_attr, num_var, num_call, num_entry );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectCallInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectCallInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectEntryInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectEntryInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectAttrInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectAttrInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectVarInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectVarInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedAttrInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedAttrInfo( lepd->idx, name, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSizeIsExprOfAttr_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* expr_str, int32_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSizeIsExprOfAttr( lepd->idx, expr_str, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfAttr_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfAttr( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedVarInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedVarInfo( lepd->idx, name, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSizeIsExprOfVar_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* expr_str, int32_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSizeIsExprOfVar( lepd->idx, expr_str, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfVar_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfVar( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* array_size)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallInfo( lepd->idx, name, max_len, array_size );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureOfCall_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureOfCall( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallSpecifierInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, bool_t* b_optional, bool_t* b_dynamic, bool_t* b_ref_desc, bool_t* b_omit)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallSpecifierInfo( lepd->idx, b_optional, b_dynamic, b_ref_desc, b_omit );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallInternalInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, bool_t* b_allocator_port, bool_t* b_require_port)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallInternalInfo( lepd->idx, b_allocator_port, b_require_port );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallLocationInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, uint32_t* offset, int8_t* place)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallLocationInfo( lepd->idx, offset, place );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallOptimizeInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, bool_t* b_VMT_useless, bool_t* b_skelton_useless, bool_t* b_cell_unique)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallOptimizeInfo( lepd->idx, b_VMT_useless, b_skelton_useless, b_cell_unique );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedEntryInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* array_size)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedEntryInfo( lepd->idx, name, max_len, array_size );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureOfEntry_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureOfEntry( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedEntryInlineInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, bool_t* b_inline)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedEntryInlineInfo( lepd->idx, b_inline );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedSignatureInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* num_function)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedSignatureInfo( lepd->idx, name, max_len, num_function );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectFunctionInfoByIndex_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectFunctionInfoByIndex( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedFunctionInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* num_args)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedFunctionInfo( lepd->idx, name, max_len, num_args );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfReturn_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfReturn( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedParamInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int8_t* dir)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedParamInfo( lepd->idx, name, max_len, dir );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectParamInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectParamInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfParam_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfParam( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedTypeInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int8_t* kind)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedTypeInfo( lepd->idx, name, max_len, kind );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfType_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfType( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedRegionInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len, int_t* num_cell, int_t* num_region)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedRegionInfo( lepd->idx, name, max_len, num_cell, num_region );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectCellInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectCellInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectRegionInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, int_t ith)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectRegionInfo( lepd->idx, ith );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCellInfo_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCellInfo( lepd->idx, name, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfoOfCell_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfoOfCell( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getAttrValueInStr_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* buf, int_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getAttrValueInStr( lepd->idx, buf, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getAttrSizeIsValue_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getAttrSizeIsValue( lepd->idx );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getVarValueInStr_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd, char_t* buf, int_t max_len)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getVarValueInStr( lepd->idx, buf, max_len );
}
ER             nTECSInfo_tTECSInfoAccessor_eSelector_getVarSizeIsValue_skel( const struct tag_nTECSInfo_sAccessor_VDES *epd)
{
    struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *lepd
        = (struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES *)epd;
    return nTECSInfo_tTECSInfoAccessor_eSelector_getVarSizeIsValue( lepd->idx );
}

/* entry port skelton function table #_EPSFT_# */
/* eSelector */
const struct tag_nTECSInfo_sAccessor_VMT nTECSInfo_tTECSInfoAccessor_eSelector_MT_ = {
    nTECSInfo_tTECSInfoAccessor_eSelector_selectNamespaceInfoByName_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfoByName_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureInfoByName_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectRegionInfoByName_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectCellInfoByName_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSignatureNameOfCellEntry_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedNamespaceInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectNamespaceInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCelltypeInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectCallInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectEntryInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectAttrInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectVarInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedAttrInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSizeIsExprOfAttr_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfAttr_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedVarInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSizeIsExprOfVar_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfVar_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureOfCall_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallSpecifierInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallInternalInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallLocationInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCallOptimizeInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedEntryInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectSignatureOfEntry_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedEntryInlineInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedSignatureInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectFunctionInfoByIndex_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedFunctionInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfReturn_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedParamInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectParamInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfParam_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedTypeInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectTypeInfoOfType_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedRegionInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectCellInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectRegionInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getSelectedCellInfo_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_selectCelltypeInfoOfCell_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getAttrValueInStr_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getAttrSizeIsValue_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getVarValueInStr_skel,
    nTECSInfo_tTECSInfoAccessor_eSelector_getVarSizeIsValue_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
char_t nTECSInfo_tTECSInfoAccessor_TECSInfoCompo_TECSInfoAccessor_CB_name_INIT[256];
char_t nTECSInfo_tTECSInfoAccessor_TECSInfoCompo_TECSInfoAccessor_CB_name2_INIT[256];
/* cell INIB #_INIB_# */
nTECSInfo_tTECSInfoAccessor_INIB nTECSInfo_tTECSInfoAccessor_INIB_tab[] = {
    /* cell: nTECSInfo_tTECSInfoAccessor_CB_tab[0]:  TECSInfoCompo_TECSInfoAccessor id=1 */
    {
        /* call port (INIB) #_CP_# */ 
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        0,                                       /* #_CCP5_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        256,                                     /* NAME_LEN */
        nTECSInfo_tTECSInfoAccessor_TECSInfoCompo_TECSInfoAccessor_CB_name_INIT, /* name */
        nTECSInfo_tTECSInfoAccessor_TECSInfoCompo_TECSInfoAccessor_CB_name2_INIT, /* name2 */
    },
};

/* cell CB #_CB_# */
struct tag_nTECSInfo_tTECSInfoAccessor_CB nTECSInfo_tTECSInfoAccessor_CB_tab[1];
/* entry port descriptor #_EPD_# */
extern const struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES rTEMP_TECSInfoCompo_TECSInfoAccessor_eSelector_des;
const struct tag_nTECSInfo_tTECSInfoAccessor_eSelector_DES rTEMP_TECSInfoCompo_TECSInfoAccessor_eSelector_des = {
    &nTECSInfo_tTECSInfoAccessor_eSelector_MT_,
    &nTECSInfo_tTECSInfoAccessor_CB_tab[0],      /* CB 3 */
};
/* CB initialize code #_CIC_# */
void
nTECSInfo_tTECSInfoAccessor_CB_initialize()
{
    nTECSInfo_tTECSInfoAccessor_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
