/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tHelloWorld_tecsgen.h"
#include "tHelloWorld_factory.h"

/* entry port descriptor type #_EDT_# */
/* eMain */
struct tag_tHelloWorld_eMain_DES {
    const struct tag_sTaskBody_VMT *vmt;
    tHelloWorld_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eMain */
void           tHelloWorld_eMain_main_skel( const struct tag_sTaskBody_VDES *epd)
{
    struct tag_tHelloWorld_eMain_DES *lepd
        = (struct tag_tHelloWorld_eMain_DES *)epd;
    tHelloWorld_eMain_main( lepd->idx );
}

/* entry port skelton function table #_EPSFT_# */
/* eMain */
const struct tag_sTaskBody_VMT tHelloWorld_eMain_MT_ = {
    tHelloWorld_eMain_main_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tHelloWorld_INIB tHelloWorld_INIB_tab[] = {
    /* cell: tHelloWorld_CB_tab[0]:  HelloWorld id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        "Good luck with TECS!\n",                /* message */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tHelloWorld_eMain_DES HelloWorld_eMain_des;
const struct tag_tHelloWorld_eMain_DES HelloWorld_eMain_des = {
    &tHelloWorld_eMain_MT_,
    &tHelloWorld_INIB_tab[0],      /* INIB 3 */
};
/* CB initialize code #_CIC_# */
void
tHelloWorld_CB_initialize()
{
    tHelloWorld_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
