inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

  DisplayCopNames: true
  #
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  #
  # 結果のsuggest部分を非表示にする
  SuggestExtensions: false
  # rubocopの対象外ファイル
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/*"
    - "config/puma.rb"
    - "root/**/*"
    - "test_data/**/*"
Layout:
  # メソッド名をcamelCase に設定します
  MethodName:
    #  EnforcedStyle: camelCase
    EnforcedStyle: snake_case
  # 一行に 120 文字まで書いても OK とする
  LineLength:
  #  Max: 120
  # Max: 150
  # Max: 170
  Max: 250

Metrics/ClassLength:
  Max: 400 # クラスの最大行数をここで設定

Style:
  # 日本語のコメントを OK とする
  AsciiComments:
    Enabled: false

  ClassAndModuleChildren:
    Enabled: false

  BlockComments:
    Enabled: false

  # class documentation commentのアラートを出さない
  Documentation:
    Enabled: false

  Naming:
    RescuedExceptionsVariableName: exc

