/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tPtrAttr_tecsgen.h"
#include "tPtrAttr_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tPtrAttr_INIB tPtrAttr_INIB_tab[] = {
    /* cell: tPtrAttr_CB_tab[0]:  PtrAttr_PtrAttr id=1 */
    {
        /* attribute(RO) */ 
        (int8_t*)0x50,                           /* p_attr0 */
        (int8_t*)0x20,                           /* p_attr1 */
        (int8_t*)0x40,                           /* p_attr2 */
        (int8_t*)0x10,                           /* p_attr3 */
    },
    /* cell: tPtrAttr_CB_tab[1]:  PtrAttr2_PtrAttr id=2 */
    {
        /* attribute(RO) */ 
        (int8_t*)0x1000,                         /* p_attr0 */
        (int8_t*)0x20,                           /* p_attr1 */
        (int8_t*)0x40,                           /* p_attr2 */
        (int8_t*)0x10,                           /* p_attr3 */
    },
};

/* entry port descriptor #_EPD_# */
