/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tSizeArray_tecsgen.h"
#include "tSizeArray_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
const const int8_t tSizeArray_SizeArray_CB_array_INIT[2] = { 0, 1, };
const const int8_t tSizeArray_CompSizeArray_Cell_CB_array_INIT[5] = { 0, };
/* cell INIB #_INIB_# */
tSizeArray_INIB tSizeArray_INIB_tab[] = {
    /* cell: tSizeArray_CB_tab[0]:  SizeArray id=1 */
    {
        /* attribute(RO) */ 
        2,                                       /* size */
        tSizeArray_SizeArray_CB_array_INIT,      /* array */
    },
    /* cell: tSizeArray_CB_tab[1]:  CompSizeArray_Cell id=2 */
    {
        /* attribute(RO) */ 
        5,                                       /* size */
        tSizeArray_CompSizeArray_Cell_CB_array_INIT, /* array */
    },
};

/* entry port descriptor #_EPD_# */
