/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "nTECSInfo_tCelltypeInfo_tecsgen.h"
#include "nTECSInfo_tCelltypeInfo_factory.h"

/* entry port descriptor type #_EDT_# */
/* eCelltypeInfo */
struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES {
    const struct tag_nTECSInfo_sCelltypeInfo_VMT *vmt;
    tCelltypeInfo_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eCelltypeInfo */
ER             nTECSInfo_tCelltypeInfo_eCelltypeInfo_getName_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getName( lepd->idx, name, max_len );
}
uint16_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNameLength_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNameLength( lepd->idx );
}
uint32_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNAttr_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNAttr( lepd->idx );
}
ER             nTECSInfo_tCelltypeInfo_eCelltypeInfo_getAttrInfo_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd, uint32_t ith, Descriptor( nTECSInfo_sVarDeclInfo )* desc)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getAttrInfo( lepd->idx, ith, desc );
}
uint32_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNVar_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNVar( lepd->idx );
}
ER             nTECSInfo_tCelltypeInfo_eCelltypeInfo_getVarInfo_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd, uint32_t ith, Descriptor( nTECSInfo_sVarDeclInfo )* desc)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getVarInfo( lepd->idx, ith, desc );
}
uint32_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNCall_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNCall( lepd->idx );
}
ER             nTECSInfo_tCelltypeInfo_eCelltypeInfo_getCallInfo_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd, uint32_t ith, Descriptor( nTECSInfo_sCallInfo )* desc)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getCallInfo( lepd->idx, ith, desc );
}
uint32_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNEntry_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNEntry( lepd->idx );
}
ER             nTECSInfo_tCelltypeInfo_eCelltypeInfo_getEntryInfo_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd, uint32_t ith, Descriptor( nTECSInfo_sEntryInfo )* desc)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_getEntryInfo( lepd->idx, ith, desc );
}
bool_t         nTECSInfo_tCelltypeInfo_eCelltypeInfo_isSingleton_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_isSingleton( lepd->idx );
}
bool_t         nTECSInfo_tCelltypeInfo_eCelltypeInfo_isIDX_is_ID_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_isIDX_is_ID( lepd->idx );
}
uint32_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_sizeOfCB_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_sizeOfCB( lepd->idx );
}
uint32_t       nTECSInfo_tCelltypeInfo_eCelltypeInfo_sizeOfINIB_skel( const struct tag_nTECSInfo_sCelltypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES *)epd;
    return nTECSInfo_tCelltypeInfo_eCelltypeInfo_sizeOfINIB( lepd->idx );
}

/* entry port skelton function table #_EPSFT_# */
/* eCelltypeInfo */
const struct tag_nTECSInfo_sCelltypeInfo_VMT nTECSInfo_tCelltypeInfo_eCelltypeInfo_MT_ = {
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getName_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNameLength_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNAttr_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getAttrInfo_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNVar_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getVarInfo_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNCall_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getCallInfo_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getNEntry_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_getEntryInfo_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_isSingleton_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_isIDX_is_ID_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_sizeOfCB_skel,
    nTECSInfo_tCelltypeInfo_eCelltypeInfo_sizeOfINIB_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_nTECSInfo_sEntryInfo_VDES rTEMP_rTECSInfo_tTask_eTaskEntryInfo_eEntryInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTask_cTaskBodyCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTask_cExceptionBodyCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_attributeVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_priorityVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_stackSizeVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_nameVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_my_threadVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_my_condVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_my_mutexVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTask_stateVarDeclInfo_eVarDeclInfo_des;

extern struct tag_nTECSInfo_sEntryInfo_VDES rTEMP_rTECSInfo_tPutStringStdio_ePutStringEntryInfo_eEntryInfo_des;

extern struct tag_nTECSInfo_sEntryInfo_VDES rTEMP_rTECSInfo_tHelloWorld_eMainEntryInfo_eEntryInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tHelloWorld_cPutStringCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tHelloWorld_messageVarDeclInfo_eVarDeclInfo_des;

extern struct tag_nTECSInfo_sEntryInfo_VDES rTEMP_rTECSInfo_tTaskMain_eBodyEntryInfo_eEntryInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cTECSInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cNSInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cRegionInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cCellInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cSignatureInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cCelltypeInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cVarDeclInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cTypeInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cPutStringCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cTaskBodyCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cREDInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_tTaskMain_cEntryInfoCallInfo_eCallInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTaskMain_NAME_LENVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTaskMain_nameVarDeclInfo_eVarDeclInfo_des;
extern struct tag_nTECSInfo_sVarDeclInfo_VDES rTEMP_rTECSInfo_tTaskMain_name2VarDeclInfo_eVarDeclInfo_des;

extern struct tag_nTECSInfo_sEntryInfo_VDES rTEMP_rTECSInfo_nTECSInfo_tTECSInfo_eTECSInfoEntryInfo_eEntryInfo_des;
extern struct tag_nTECSInfo_sCallInfo_VDES rTEMP_rTECSInfo_nTECSInfo_tTECSInfo_cTECSInfoCallInfo_eCallInfo_des;

/* call port array #_CPA_# */
struct tag_nTECSInfo_sEntryInfo_VDES * const rTEMP_rTECSInfo_tTaskCelltypeInfo_cEntryInfo[] = {
    &rTEMP_rTECSInfo_tTask_eTaskEntryInfo_eEntryInfo_des,
};
struct tag_nTECSInfo_sCallInfo_VDES * const rTEMP_rTECSInfo_tTaskCelltypeInfo_cCallInfo[] = {
    &rTEMP_rTECSInfo_tTask_cTaskBodyCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTask_cExceptionBodyCallInfo_eCallInfo_des,
};
struct tag_nTECSInfo_sVarDeclInfo_VDES * const rTEMP_rTECSInfo_tTaskCelltypeInfo_cAttrInfo[] = {
    &rTEMP_rTECSInfo_tTask_attributeVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTask_priorityVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTask_stackSizeVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTask_nameVarDeclInfo_eVarDeclInfo_des,
};
struct tag_nTECSInfo_sVarDeclInfo_VDES * const rTEMP_rTECSInfo_tTaskCelltypeInfo_cVarInfo[] = {
    &rTEMP_rTECSInfo_tTask_my_threadVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTask_my_condVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTask_my_mutexVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTask_stateVarDeclInfo_eVarDeclInfo_des,
};

struct tag_nTECSInfo_sEntryInfo_VDES * const rTEMP_rTECSInfo_tPutStringStdioCelltypeInfo_cEntryInfo[] = {
    &rTEMP_rTECSInfo_tPutStringStdio_ePutStringEntryInfo_eEntryInfo_des,
};

struct tag_nTECSInfo_sEntryInfo_VDES * const rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_cEntryInfo[] = {
    &rTEMP_rTECSInfo_tHelloWorld_eMainEntryInfo_eEntryInfo_des,
};
struct tag_nTECSInfo_sCallInfo_VDES * const rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_cCallInfo[] = {
    &rTEMP_rTECSInfo_tHelloWorld_cPutStringCallInfo_eCallInfo_des,
};
struct tag_nTECSInfo_sVarDeclInfo_VDES * const rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_cAttrInfo[] = {
    &rTEMP_rTECSInfo_tHelloWorld_messageVarDeclInfo_eVarDeclInfo_des,
};

struct tag_nTECSInfo_sEntryInfo_VDES * const rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cEntryInfo[] = {
    &rTEMP_rTECSInfo_tTaskMain_eBodyEntryInfo_eEntryInfo_des,
};
struct tag_nTECSInfo_sCallInfo_VDES * const rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cCallInfo[] = {
    &rTEMP_rTECSInfo_tTaskMain_cTECSInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cNSInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cRegionInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cCellInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cSignatureInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cCelltypeInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cVarDeclInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cTypeInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cPutStringCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cTaskBodyCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cREDInfoCallInfo_eCallInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_cEntryInfoCallInfo_eCallInfo_des,
};
struct tag_nTECSInfo_sVarDeclInfo_VDES * const rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cAttrInfo[] = {
    &rTEMP_rTECSInfo_tTaskMain_NAME_LENVarDeclInfo_eVarDeclInfo_des,
};
struct tag_nTECSInfo_sVarDeclInfo_VDES * const rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cVarInfo[] = {
    &rTEMP_rTECSInfo_tTaskMain_nameVarDeclInfo_eVarDeclInfo_des,
    &rTEMP_rTECSInfo_tTaskMain_name2VarDeclInfo_eVarDeclInfo_des,
};

struct tag_nTECSInfo_sEntryInfo_VDES * const rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_cEntryInfo[] = {
    &rTEMP_rTECSInfo_nTECSInfo_tTECSInfo_eTECSInfoEntryInfo_eEntryInfo_des,
};
struct tag_nTECSInfo_sCallInfo_VDES * const rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_cCallInfo[] = {
    &rTEMP_rTECSInfo_nTECSInfo_tTECSInfo_cTECSInfoCallInfo_eCallInfo_des,
};

/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_nTECSInfo_tCelltypeInfo_CB nTECSInfo_tCelltypeInfo_CB_tab[] = {
    /* cell: nTECSInfo_tCelltypeInfo_CB_tab[0]:  tTaskCelltypeInfo id=1 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        rTEMP_rTECSInfo_tTaskCelltypeInfo_cEntryInfo, /* #_CCP3B_# */
        1,                                       /* length of cEntryInfo (n_cEntryInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tTaskCelltypeInfo_cCallInfo, /* #_CCP3B_# */
        2,                                       /* length of cCallInfo (n_cCallInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tTaskCelltypeInfo_cAttrInfo, /* #_CCP3B_# */
        4,                                       /* length of cAttrInfo (n_cAttrInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tTaskCelltypeInfo_cVarInfo, /* #_CCP3B_# */
        4,                                       /* length of cVarInfo (n_cVarInfo) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "tTask",                                 /* name */
        false,                                   /* b_singleton */
        tTask__IDX_is_ID_act,                    /* b_IDX_is_ID_act */
        tTask__sizeOfCB,                         /* sizeOfCB */
        tTask__sizeOfINIB,                       /* sizeOfINIB */
        tTask__NCELLINLINKUNIT,                  /* n_cellInLinkUnit */
        1,                                       /* n_cellInSystem */
    },
    /* cell: nTECSInfo_tCelltypeInfo_CB_tab[1]:  tPutStringStdioCelltypeInfo id=2 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        rTEMP_rTECSInfo_tPutStringStdioCelltypeInfo_cEntryInfo, /* #_CCP3B_# */
        1,                                       /* length of cEntryInfo (n_cEntryInfo) #_CCP4_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cCallInfo (n_cCallInfo) #_CCP6_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cAttrInfo (n_cAttrInfo) #_CCP6_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cVarInfo (n_cVarInfo) #_CCP6_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "tPutStringStdio",                       /* name */
        false,                                   /* b_singleton */
        tPutStringStdio__IDX_is_ID_act,          /* b_IDX_is_ID_act */
        tPutStringStdio__sizeOfCB,               /* sizeOfCB */
        tPutStringStdio__sizeOfINIB,             /* sizeOfINIB */
        tPutStringStdio__NCELLINLINKUNIT,        /* n_cellInLinkUnit */
        1,                                       /* n_cellInSystem */
    },
    /* cell: nTECSInfo_tCelltypeInfo_CB_tab[2]:  tHelloWorldCelltypeInfo id=3 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_cEntryInfo, /* #_CCP3B_# */
        1,                                       /* length of cEntryInfo (n_cEntryInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_cCallInfo, /* #_CCP3B_# */
        1,                                       /* length of cCallInfo (n_cCallInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_cAttrInfo, /* #_CCP3B_# */
        1,                                       /* length of cAttrInfo (n_cAttrInfo) #_CCP4_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cVarInfo (n_cVarInfo) #_CCP6_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "tHelloWorld",                           /* name */
        false,                                   /* b_singleton */
        tHelloWorld__IDX_is_ID_act,              /* b_IDX_is_ID_act */
        tHelloWorld__sizeOfCB,                   /* sizeOfCB */
        tHelloWorld__sizeOfINIB,                 /* sizeOfINIB */
        tHelloWorld__NCELLINLINKUNIT,            /* n_cellInLinkUnit */
        1,                                       /* n_cellInSystem */
    },
    /* cell: nTECSInfo_tCelltypeInfo_CB_tab[3]:  tTaskMainCelltypeInfo id=4 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cEntryInfo, /* #_CCP3B_# */
        1,                                       /* length of cEntryInfo (n_cEntryInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cCallInfo, /* #_CCP3B_# */
        12,                                      /* length of cCallInfo (n_cCallInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cAttrInfo, /* #_CCP3B_# */
        1,                                       /* length of cAttrInfo (n_cAttrInfo) #_CCP4_# */
        rTEMP_rTECSInfo_tTaskMainCelltypeInfo_cVarInfo, /* #_CCP3B_# */
        2,                                       /* length of cVarInfo (n_cVarInfo) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "tTaskMain",                             /* name */
        false,                                   /* b_singleton */
        tTaskMain__IDX_is_ID_act,                /* b_IDX_is_ID_act */
        tTaskMain__sizeOfCB,                     /* sizeOfCB */
        tTaskMain__sizeOfINIB,                   /* sizeOfINIB */
        tTaskMain__NCELLINLINKUNIT,              /* n_cellInLinkUnit */
        1,                                       /* n_cellInSystem */
    },
    /* cell: nTECSInfo_tCelltypeInfo_CB_tab[4]:  nTECSInfo_tTECSInfoCelltypeInfo id=5 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_cEntryInfo, /* #_CCP3B_# */
        1,                                       /* length of cEntryInfo (n_cEntryInfo) #_CCP4_# */
        rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_cCallInfo, /* #_CCP3B_# */
        1,                                       /* length of cCallInfo (n_cCallInfo) #_CCP4_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cAttrInfo (n_cAttrInfo) #_CCP6_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cVarInfo (n_cVarInfo) #_CCP6_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "tTECSInfo",                             /* name */
        true,                                    /* b_singleton */
        nTECSInfo_tTECSInfo__IDX_is_ID_act,      /* b_IDX_is_ID_act */
        nTECSInfo_tTECSInfo__sizeOfCB,           /* sizeOfCB */
        nTECSInfo_tTECSInfo__sizeOfINIB,         /* sizeOfINIB */
        nTECSInfo_tTECSInfo__NCELLINLINKUNIT,    /* n_cellInLinkUnit */
        1,                                       /* n_cellInSystem */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tTaskCelltypeInfo_eCelltypeInfo_des;
const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tTaskCelltypeInfo_eCelltypeInfo_des = {
    &nTECSInfo_tCelltypeInfo_eCelltypeInfo_MT_,
    &nTECSInfo_tCelltypeInfo_CB_tab[0],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tPutStringStdioCelltypeInfo_eCelltypeInfo_des;
const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tPutStringStdioCelltypeInfo_eCelltypeInfo_des = {
    &nTECSInfo_tCelltypeInfo_eCelltypeInfo_MT_,
    &nTECSInfo_tCelltypeInfo_CB_tab[1],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_eCelltypeInfo_des;
const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_eCelltypeInfo_des = {
    &nTECSInfo_tCelltypeInfo_eCelltypeInfo_MT_,
    &nTECSInfo_tCelltypeInfo_CB_tab[2],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tTaskMainCelltypeInfo_eCelltypeInfo_des;
const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_tTaskMainCelltypeInfo_eCelltypeInfo_des = {
    &nTECSInfo_tCelltypeInfo_eCelltypeInfo_MT_,
    &nTECSInfo_tCelltypeInfo_CB_tab[3],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_eCelltypeInfo_des;
const struct tag_nTECSInfo_tCelltypeInfo_eCelltypeInfo_DES rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_eCelltypeInfo_des = {
    &nTECSInfo_tCelltypeInfo_eCelltypeInfo_MT_,
    &nTECSInfo_tCelltypeInfo_CB_tab[4],      /* CB 3 */
};
