/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "nTECSInfo_tDefinedTypeInfo_tecsgen.h"
#include "nTECSInfo_tDefinedTypeInfo_factory.h"

/* entry port descriptor type #_EDT_# */
/* eTypeInfo */
struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES {
    const struct tag_nTECSInfo_sTypeInfo_VMT *vmt;
    tDefinedTypeInfo_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eTypeInfo */
ER             nTECSInfo_tDefinedTypeInfo_eTypeInfo_getName_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getName( lepd->idx, name, max_len );
}
uint16_t       nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNameLength_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNameLength( lepd->idx );
}
uint32_t       nTECSInfo_tDefinedTypeInfo_eTypeInfo_getSize_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getSize( lepd->idx );
}
int8_t         nTECSInfo_tDefinedTypeInfo_eTypeInfo_getKind_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getKind( lepd->idx );
}
uint32_t       nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNType_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNType( lepd->idx );
}
ER             nTECSInfo_tDefinedTypeInfo_eTypeInfo_getTypeInfo_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd, Descriptor( nTECSInfo_sTypeInfo )* desc)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getTypeInfo( lepd->idx, desc );
}
uint32_t       nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNMember_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNMember( lepd->idx );
}
ER             nTECSInfo_tDefinedTypeInfo_eTypeInfo_getMemberInfo_skel( const struct tag_nTECSInfo_sTypeInfo_VDES *epd, uint32_t ith, Descriptor( nTECSInfo_sVarDeclInfo )* desc)
{
    struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *lepd
        = (struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES *)epd;
    return nTECSInfo_tDefinedTypeInfo_eTypeInfo_getMemberInfo( lepd->idx, ith, desc );
}

/* entry port skelton function table #_EPSFT_# */
/* eTypeInfo */
const struct tag_nTECSInfo_sTypeInfo_VMT nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_ = {
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getName_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNameLength_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getSize_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getKind_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNType_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getTypeInfo_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getNMember_skel,
    nTECSInfo_tDefinedTypeInfo_eTypeInfo_getMemberInfo_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_unsigned__intTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_signed__intTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ulong_tTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_unsigned__longTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ulong_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_struct__t_rsemTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_struct__t_rflgTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_longTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_struct__t_rdtqTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des;

extern struct tag_nTECSInfo_sTypeInfo_VDES rTEMP_rTECSInfo_unsigned__longTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des;

extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des;

/* call port array #_CPA_# */






















/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_nTECSInfo_tDefinedTypeInfo_CB nTECSInfo_tDefinedTypeInfo_CB_tab[] = {
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[0]:  TEXPTNTypeInfo id=1 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "TEXPTN",                                /* name */
        6,                                       /* typeKind */
        sizeof(TEXPTN),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[1]:  uint_tTypeInfo id=2 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_unsigned__intTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "uint_t",                                /* name */
        6,                                       /* typeKind */
        sizeof(uint_t),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[2]:  ERTypeInfo id=3 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "ER",                                    /* name */
        6,                                       /* typeKind */
        sizeof(ER),                              /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[3]:  int_tTypeInfo id=4 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_signed__intTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "int_t",                                 /* name */
        6,                                       /* typeKind */
        sizeof(int_t),                           /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[4]:  RELTIMTypeInfo id=5 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "RELTIM",                                /* name */
        6,                                       /* typeKind */
        sizeof(RELTIM),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[5]:  SYSTIMTypeInfo id=6 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_ulong_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "SYSTIM",                                /* name */
        6,                                       /* typeKind */
        sizeof(SYSTIM),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[6]:  ulong_tTypeInfo id=7 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_unsigned__longTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "ulong_t",                               /* name */
        6,                                       /* typeKind */
        sizeof(ulong_t),                         /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[7]:  SYSUTMTypeInfo id=8 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_ulong_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "SYSUTM",                                /* name */
        6,                                       /* typeKind */
        sizeof(SYSUTM),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[8]:  TMOTypeInfo id=9 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "TMO",                                   /* name */
        6,                                       /* typeKind */
        sizeof(TMO),                             /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[9]:  T_RSEMTypeInfo id=10 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_struct__t_rsemTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "T_RSEM",                                /* name */
        6,                                       /* typeKind */
        sizeof(T_RSEM),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[10]:  IDTypeInfo id=11 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "ID",                                    /* name */
        6,                                       /* typeKind */
        sizeof(ID),                              /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[11]:  FLGPTNTypeInfo id=12 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "FLGPTN",                                /* name */
        6,                                       /* typeKind */
        sizeof(FLGPTN),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[12]:  MODETypeInfo id=13 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "MODE",                                  /* name */
        6,                                       /* typeKind */
        sizeof(MODE),                            /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[13]:  T_RFLGTypeInfo id=14 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_struct__t_rflgTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "T_RFLG",                                /* name */
        6,                                       /* typeKind */
        sizeof(T_RFLG),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[14]:  intptr_tTypeInfo id=15 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_longTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "intptr_t",                              /* name */
        6,                                       /* typeKind */
        sizeof(intptr_t),                        /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[15]:  T_RDTQTypeInfo id=16 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_struct__t_rdtqTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "T_RDTQ",                                /* name */
        6,                                       /* typeKind */
        sizeof(T_RDTQ),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[16]:  ATRTypeInfo id=17 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "ATR",                                   /* name */
        6,                                       /* typeKind */
        sizeof(ATR),                             /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[17]:  PRITypeInfo id=18 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "PRI",                                   /* name */
        6,                                       /* typeKind */
        sizeof(PRI),                             /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[18]:  size_tTypeInfo id=19 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_unsigned__longTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "size_t",                                /* name */
        6,                                       /* typeKind */
        sizeof(size_t),                          /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[19]:  pthread_tTypeInfo id=20 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "pthread_t",                             /* name */
        6,                                       /* typeKind */
        sizeof(pthread_t),                       /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[20]:  pthread_cond_tTypeInfo id=21 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "pthread_cond_t",                        /* name */
        6,                                       /* typeKind */
        sizeof(pthread_cond_t),                  /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
    /* cell: nTECSInfo_tDefinedTypeInfo_CB_tab[21]:  pthread_mutex_tTypeInfo id=22 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        (struct tag_nTECSInfo_sTypeInfo_VDES *)&rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des, /* cTypeInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "pthread_mutex_t",                       /* name */
        6,                                       /* typeKind */
        sizeof(pthread_mutex_t),                 /* size */
        false,                                   /* b_const */
        false,                                   /* b_volatile */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_TEXPTNTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_TEXPTNTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[0],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_uint_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[1],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ERTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ERTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[2],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_int_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[3],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_RELTIMTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_RELTIMTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[4],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_SYSTIMTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_SYSTIMTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[5],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ulong_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ulong_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[6],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_SYSUTMTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_SYSUTMTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[7],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_TMOTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_TMOTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[8],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_T_RSEMTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_T_RSEMTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[9],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_IDTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_IDTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[10],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_FLGPTNTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_FLGPTNTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[11],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_MODETypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_MODETypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[12],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_T_RFLGTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_T_RFLGTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[13],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_intptr_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[14],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_T_RDTQTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_T_RDTQTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[15],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ATRTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_ATRTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[16],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_PRITypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_PRITypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[17],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_size_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_size_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[18],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_pthread_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_pthread_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[19],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_pthread_cond_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_pthread_cond_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[20],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_pthread_mutex_tTypeInfo_eTypeInfo_des;
const struct tag_nTECSInfo_tDefinedTypeInfo_eTypeInfo_DES rTEMP_rTECSInfo_pthread_mutex_tTypeInfo_eTypeInfo_des = {
    &nTECSInfo_tDefinedTypeInfo_eTypeInfo_MT_,
    &nTECSInfo_tDefinedTypeInfo_CB_tab[21],      /* CB 3 */
};
