/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tHelloWorld_TECSGEN_H
#define tHelloWorld_TECSGEN_H

/*
 * celltype          :  tHelloWorld
 * global name       :  tHelloWorld
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sTaskBody_tecsgen.h"
#include "sPutString_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tHelloWorld_CB {
    /* call port #_TCP_# */
    /* call port #_NEP_# */ 
    /* attribute #_AT_# */ 
    char_t*        message;
}  tHelloWorld_CB;
/* singleton cell CB prototype declaration #_MCPB_# */
extern tHelloWorld_CB  tHelloWorld_CB_tab[];

/* celltype IDX type #_CTIX_# */
typedef struct tag_tHelloWorld_CB *tHelloWorld_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sTaskBody */
void         tHelloWorld_eMain_main(tHelloWorld_IDX idx);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tHelloWorld_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tPutStringStdio_tecsgen.h"
#ifdef  tHelloWorld_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tHelloWorld_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tHelloWorld_ID_BASE         (1)  /* ID Base  #_NIDB_# */
#define tHelloWorld_N_CELL          (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tHelloWorld_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tHelloWorld_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tHelloWorld_ATTR_message( p_that )	((p_that)->message)

#define tHelloWorld_GET_message(p_that)	((p_that)->message)



#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tHelloWorld_cPutString_putString( p_that, string ) \
	  tPutStringStdio_ePutString_putString( \
	   (tPutStringStdio_IDX)0, (string) )

#else  /* TECSFLOW */
#define tHelloWorld_cPutString_putString( p_that, string ) \
	  (p_that)->cPutString.putString__T( \
 (string) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
void           tHelloWorld_eMain_main_skel( const struct tag_sTaskBody_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tHelloWorld_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tHelloWorld_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tHelloWorld_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tHelloWorld_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_message         tHelloWorld_ATTR_message( p_cellcb )


/* call port function macro (abbrev) #_CPMA_# */
#define cPutString_putString( string ) \
          ((void)p_cellcb, tHelloWorld_cPutString_putString( p_cellcb, string ))




/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tHelloWorld_eMain_main

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tHelloWorld_N_CELL; (i)++ ){ \
       (p_cb) = &tHelloWorld_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tHelloWorld_TECSGENH */
