/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tAttribute4_tecsgen.h"
#include "tAttribute4_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_tAttribute4_CB tAttribute4_CB_tab[] = {
    /* cell: tAttribute4_CB_tab[0]:  Attr4 id=1 */
    {
        /* attribute */ 
        {
            0,                                       /* buf0[0] */
            0,                                       /* buf0[1] */
        },
    },
};

/* entry port descriptor #_EPD_# */
