/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tAttributeSt_tecsgen.h"
#include "tAttributeSt_factory.h"

/* entry port descriptor type #_EDT_# */
/* eMain */
struct tag_tAttributeSt_eMain_DES {
    const struct tag_sMain_VMT *vmt;
    tAttributeSt_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eMain */
ER             tAttributeSt_eMain_main_skel( const struct tag_sMain_VDES *epd)
{
    struct tag_tAttributeSt_eMain_DES *lepd
        = (struct tag_tAttributeSt_eMain_DES *)epd;
    return tAttributeSt_eMain_main( lepd->idx );
}

/* entry port skelton function table #_EPSFT_# */
/* eMain */
const struct tag_sMain_VMT tAttributeSt_eMain_MT_ = {
    tAttributeSt_eMain_main_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
const const struct tTag tAttributeSt_tst_CB_st_array_INIT[2] = { { 1, }, { 2, }, };
const const struct tTag tAttributeSt_tst2_CB_st_array_INIT[3] = { { 100, }, };
/* cell CB #_CB_# */
struct tag_tAttributeSt_CB tAttributeSt_CB_tab[] = {
    /* cell: tAttributeSt_CB_tab[0]:  tst id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute */ 
        2,                                       /* size */
        tAttributeSt_tst_CB_st_array_INIT,       /* st_array */
    },
    /* cell: tAttributeSt_CB_tab[1]:  tst2 id=2 */
    {
        /* entry port #_EP_# */ 
        /* attribute */ 
        3,                                       /* size */
        tAttributeSt_tst2_CB_st_array_INIT,      /* st_array */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tAttributeSt_eMain_DES tst_eMain_des;
const struct tag_tAttributeSt_eMain_DES tst_eMain_des = {
    &tAttributeSt_eMain_MT_,
    &tAttributeSt_CB_tab[0],      /* CB 3 */
};
extern const struct tag_tAttributeSt_eMain_DES tst2_eMain_des;
const struct tag_tAttributeSt_eMain_DES tst2_eMain_des = {
    &tAttributeSt_eMain_MT_,
    &tAttributeSt_CB_tab[1],      /* CB 3 */
};
