/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tAttribute_templ.c => src/tAttribute.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * size             uint32_t         ATTR_size       
 * size2            uint32_t         ATTR_size2      
 * size_array       const int32_t*   ATTR_size_array 
 * ptr              volatile int32_t*  ATTR_ptr        
 * very_long_name_more_than_16char int32_t          ATTR_very_long_name_more_than_16char
 * msg              char_t*          ATTR_msg        
 * sz_array         int32_t*         VAR_sz_array    
 * st               T                VAR_st          
 * msg2             char_t*          VAR_msg2        
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tAttribute_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eMain
 * entry port: eMain
 * signature:  sMain
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eMain_main
 * name:         eMain_main
 * global_name:  tAttribute_eMain_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eMain_main(CELLIDX idx)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return(ercd);
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
