/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCEXP_tecsgen.h"
#include "tCEXP_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */



/* call port array #_CPA_# */



/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_tCEXP_CB tCEXP_CB_tab[] = {
    /* cell: tCEXP_CB_tab[0]:  CEXP id=1 */
    {
        /* attribute */ 
        DEFINED_INTVAL,                          /* val */
        /* var */ 
        DEFINED_INTVAL,                          /* vval */
    },
    /* cell: tCEXP_CB_tab[1]:  CEXP2 id=2 */
    {
        /* attribute */ 
        NOTDEFINED_INTVAL,                       /* val */
        /* var */ 
        NOTDEFINED_INTVAL,                       /* vval */
    },
    /* cell: tCEXP_CB_tab[2]:  CEXP3 id=3 */
    {
        /* attribute */ 
        CONST_INTVAL,                            /* val */
        /* var */ 
        CONST_INTVAL,                            /* vval */
    },
};

/* entry port descriptor #_EPD_# */
