/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCt_no_CB_no_INIB_tecsgen.h"
#include "tCt_no_CB_no_INIB_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
int8_t Ct_no_CB_no_INIB_CB_buf_INIT[1];
/* cell INIB #_INIB_# */
/* cell: Ct_no_CB_no_INIB_CB:  Ct_no_CB_no_INIB id=16 */
const tCt_no_CB_no_INIB_INIB Ct_no_CB_no_INIB_INIB = {
    /* attribute(RO) */ 
    Ct_no_CB_no_INIB_CB_buf_INIT,            /* buf */
};

/* entry port descriptor #_EPD_# */
/* ID to INIB table #_INTAB_# */
tCt_no_CB_no_INIB_INIB *const tCt_no_CB_no_INIB_INIB_ptab[] ={
    &Ct_no_CB_no_INIB_INIB,
};
/* CB initialize code #_CIC_# */
void
tCt_no_CB_no_INIB_CB_initialize()
{
    tCt_no_CB_no_INIB_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
