/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tTask_tecsgen.h"
#include "tTask_factory.h"

/* entry port descriptor type #_EDT_# */
/* eTask : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eTask : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eTask : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tTask_INIB tTask_INIB_tab[] = {
    /* cell: tTask_CB_tab[0]:  Task_Task id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        TA_ACT,                                  /* attribute */
        11,                                      /* priority */
        256,                                     /* stackSize */
        "tTask_Task_Task",                       /* name */
    },
};

/* cell CB #_CB_# */
struct tag_tTask_CB tTask_CB_tab[1];
/* entry port descriptor #_EPD_# */
/* eTask : omitted by entry port optimize */
/* CB initialize code #_CIC_# */
void
tTask_CB_initialize()
{
    tTask_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
