/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tAlloc_tecsgen.h"
#include "tAlloc_factory.h"

/* entry port descriptor type #_EDT_# */
/* eA : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eA : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eA : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
int8_t tAlloc_Alloc_CB_buffer_INIT[8192];
/* cell CB #_CB_# */
struct tag_tAlloc_CB tAlloc_CB_tab[] = {
    /* cell: tAlloc_CB_tab[0]:  Alloc id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute */ 
        8192,                                    /* size */
        tAlloc_Alloc_CB_buffer_INIT,             /* buffer */
    },
};

/* entry port descriptor #_EPD_# */
/* eA : omitted by entry port optimize */
