/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tSendRecvServ_templ.c => src/tSendRecvServ.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * allocator port for call port:eEnt func:snd param: st_val
 *   ER             eEnt_snd_st_val_alloc( int32_t size, void** p );
 *   ER             eEnt_snd_st_val_dealloc( const void* p );
 * allocator port for call port:eEnt func:rcv param: st_val
 *   ER             eEnt_rcv_st_val_alloc( int32_t size, void** p );
 *   ER             eEnt_rcv_st_val_dealloc( const void* p );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tSendRecvServ_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eEnt
 * entry port: eEnt
 * signature:  sSigSendRecv
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eEnt_snd
 * name:         eEnt_snd
 * global_name:  tSendRecvServ_eEnt_snd
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eEnt_snd(CELLIDX idx, ST_VAL* st_val)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return(ercd);
}

/* #[<ENTRY_FUNC>]# eEnt_rcv
 * name:         eEnt_rcv
 * global_name:  tSendRecvServ_eEnt_rcv
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eEnt_rcv(CELLIDX idx, ST_VAL** st_val)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return(ercd);
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
