/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tVMTUselessOptimizeCallee_TECSGEN_H
#define tVMTUselessOptimizeCallee_TECSGEN_H

/*
 * celltype          :  tVMTUselessOptimizeCallee
 * global name       :  tVMTUselessOptimizeCallee
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sSig_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tVMTUselessOptimizeCallee_CB {
    /* call port #_NEP_# */ 
    /* attribute #_AT_# */ 
    int32_t        attribute;
}  tVMTUselessOptimizeCallee_CB;
/* singleton cell CB prototype declaration #_MCPB_# */
extern tVMTUselessOptimizeCallee_CB  tVMTUselessOptimizeCallee_CB_tab[];

/* celltype IDX type #_CTIX_# */
typedef struct tag_tVMTUselessOptimizeCallee_CB *tVMTUselessOptimizeCallee_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sSig */
void         tVMTUselessOptimizeCallee_eEnt_func(tVMTUselessOptimizeCallee_IDX idx, int_t subscript);
int32_t      tVMTUselessOptimizeCallee_eEnt_func2(tVMTUselessOptimizeCallee_IDX idx, int_t subscript, int32_t arg);
struct tagST tVMTUselessOptimizeCallee_eEnt_func3(tVMTUselessOptimizeCallee_IDX idx, int_t subscript, struct tagST a);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tVMTUselessOptimizeCallee_ID_BASE        (1)  /* ID Base  #_NIDB_# */
#define tVMTUselessOptimizeCallee_N_CELL        (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tVMTUselessOptimizeCallee_VALID_IDX(IDX) (1)

/* entry port array size macro #_NEPA_# */
#define NEP_eEnt     (2)

/* celll CB macro #_GCB_# */
#define tVMTUselessOptimizeCallee_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tVMTUselessOptimizeCallee_ATTR_attribute( p_that )	((p_that)->attribute)

#define tVMTUselessOptimizeCallee_GET_attribute(p_that)	((p_that)->attribute)



#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eEnt */
void           tVMTUselessOptimizeCallee_eEnt_func_skel( const struct tag_sSig_VDES *epd);
int32_t        tVMTUselessOptimizeCallee_eEnt_func2_skel( const struct tag_sSig_VDES *epd, int32_t arg);
struct tagST   tVMTUselessOptimizeCallee_eEnt_func3_skel( const struct tag_sSig_VDES *epd, struct tagST a);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tVMTUselessOptimizeCallee_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tVMTUselessOptimizeCallee_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tVMTUselessOptimizeCallee_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tVMTUselessOptimizeCallee_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_attribute       tVMTUselessOptimizeCallee_ATTR_attribute( p_cellcb )





/* entry port function macro (abbrev) #_EPM_# */
#define eEnt_func        tVMTUselessOptimizeCallee_eEnt_func
#define eEnt_func2       tVMTUselessOptimizeCallee_eEnt_func2
#define eEnt_func3       tVMTUselessOptimizeCallee_eEnt_func3

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tVMTUselessOptimizeCallee_N_CELL; (i)++ ){ \
       (p_cb) = &tVMTUselessOptimizeCallee_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tVMTUselessOptimizeCallee_TECSGENH */
