/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCell3_tecsgen.h"
#include "tCell3_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntry3 */
struct tag_tCell3_eEntry3_DES {
    const struct tag_sSig3_VMT *vmt;
    tCell3_IDX  idx;
    int_t  subscript;
};

/* entry port skelton function #_EPSF_# */
/* eEntry3 */
int32_t        tCell3_eEntry3_func1_skel( const struct tag_sSig3_VDES *epd, int32_t a)
{
    struct tag_tCell3_eEntry3_DES *lepd
        = (struct tag_tCell3_eEntry3_DES *)epd;
    return tCell3_eEntry3_func1( lepd->idx, lepd->subscript, a );
}
int32_t        tCell3_eEntry3_func2_skel( const struct tag_sSig3_VDES *epd, int32_t a)
{
    struct tag_tCell3_eEntry3_DES *lepd
        = (struct tag_tCell3_eEntry3_DES *)epd;
    return tCell3_eEntry3_func2( lepd->idx, lepd->subscript, a );
}

/* entry port skelton function table #_EPSFT_# */
/* eEntry3 */
const struct tag_sSig3_VMT tCell3_eEntry3_MT_ = {
    tCell3_eEntry3_func1_skel,
    tCell3_eEntry3_func2_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_sSig4_VDES comp1_comp12_cell4_eEntry4_des;
extern struct tag_sSigB_VDES comp1_comp11_cell2_eEntryB_des;

extern struct tag_sSig4_VDES comp2_comp12_cell4_eEntry4_des;
extern struct tag_sSigB_VDES comp2_comp11_cell2_eEntryB_des;

/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
/* cell: comp1_comp12_cell3_CB:  comp1_comp12_cell3 id=5 */
const tCell3_INIB comp1_comp12_cell3_INIB = {
    /* call port (INIB) #_CP_# */ 
    7,                                       /* cCall3 #_CCP2_# */
    3,                                       /* cCallB #_CCP2_# */
    /* entry port #_EP_# */ 
    /* attribute(RO) */ 
    30,                                      /* a */
};

/* cell: comp2_comp12_cell3_CB:  comp2_comp12_cell3 id=6 */
const tCell3_INIB comp2_comp12_cell3_INIB = {
    /* call port (INIB) #_CP_# */ 
    8,                                       /* cCall3 #_CCP2_# */
    4,                                       /* cCallB #_CCP2_# */
    /* entry port #_EP_# */ 
    /* attribute(RO) */ 
    30,                                      /* a */
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tCell3_eEntry3_DES comp1_comp12_cell3_eEntry3_des0;
const struct tag_tCell3_eEntry3_DES comp1_comp12_cell3_eEntry3_des0 = {
    &tCell3_eEntry3_MT_,
    5,           /* ID */
    0
};
extern const struct tag_tCell3_eEntry3_DES comp1_comp12_cell3_eEntry3_des1;
const struct tag_tCell3_eEntry3_DES comp1_comp12_cell3_eEntry3_des1 = {
    &tCell3_eEntry3_MT_,
    5,           /* ID */
    1
};
extern const struct tag_tCell3_eEntry3_DES comp2_comp12_cell3_eEntry3_des0;
const struct tag_tCell3_eEntry3_DES comp2_comp12_cell3_eEntry3_des0 = {
    &tCell3_eEntry3_MT_,
    6,           /* ID */
    0
};
extern const struct tag_tCell3_eEntry3_DES comp2_comp12_cell3_eEntry3_des1;
const struct tag_tCell3_eEntry3_DES comp2_comp12_cell3_eEntry3_des1 = {
    &tCell3_eEntry3_MT_,
    6,           /* ID */
    1
};
/* ID to INIB table #_INTAB_# */
tCell3_INIB *const tCell3_INIB_ptab[] ={
    &comp1_comp12_cell3_INIB,
    &comp2_comp12_cell3_INIB,
};
