/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "nTECSInfo_tCellInfo_tecsgen.h"
#include "nTECSInfo_tCellInfo_factory.h"

/* entry port descriptor type #_EDT_# */
/* eCellInfo */
struct tag_nTECSInfo_tCellInfo_eCellInfo_DES {
    const struct tag_nTECSInfo_sCellInfo_VMT *vmt;
    tCellInfo_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eCellInfo */
ER             nTECSInfo_tCellInfo_eCellInfo_getName_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    return nTECSInfo_tCellInfo_eCellInfo_getName( lepd->idx, name, max_len );
}
uint16_t       nTECSInfo_tCellInfo_eCellInfo_getNameLength_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    return nTECSInfo_tCellInfo_eCellInfo_getNameLength( lepd->idx );
}
uint32_t       nTECSInfo_tCellInfo_eCellInfo_getNRawEntryDescriptorInfo_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    return nTECSInfo_tCellInfo_eCellInfo_getNRawEntryDescriptorInfo( lepd->idx );
}
ER             nTECSInfo_tCellInfo_eCellInfo_getRawEntryDescriptorInfo_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd, int_t index, Descriptor( nTECSInfo_sRawEntryDescriptorInfo )* desc)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    return nTECSInfo_tCellInfo_eCellInfo_getRawEntryDescriptorInfo( lepd->idx, index, desc );
}
void           nTECSInfo_tCellInfo_eCellInfo_getCelltypeInfo_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd, Descriptor( nTECSInfo_sCelltypeInfo )* desc)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    nTECSInfo_tCellInfo_eCellInfo_getCelltypeInfo( lepd->idx, desc );
}
void           nTECSInfo_tCellInfo_eCellInfo_getCBP_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd, void** cbp)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    nTECSInfo_tCellInfo_eCellInfo_getCBP( lepd->idx, cbp );
}
void           nTECSInfo_tCellInfo_eCellInfo_getINIBP_skel( const struct tag_nTECSInfo_sCellInfo_VDES *epd, void** inibp)
{
    struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *lepd
        = (struct tag_nTECSInfo_tCellInfo_eCellInfo_DES *)epd;
    nTECSInfo_tCellInfo_eCellInfo_getINIBP( lepd->idx, inibp );
}

/* entry port skelton function table #_EPSFT_# */
/* eCellInfo */
const struct tag_nTECSInfo_sCellInfo_VMT nTECSInfo_tCellInfo_eCellInfo_MT_ = {
    nTECSInfo_tCellInfo_eCellInfo_getName_skel,
    nTECSInfo_tCellInfo_eCellInfo_getNameLength_skel,
    nTECSInfo_tCellInfo_eCellInfo_getNRawEntryDescriptorInfo_skel,
    nTECSInfo_tCellInfo_eCellInfo_getRawEntryDescriptorInfo_skel,
    nTECSInfo_tCellInfo_eCellInfo_getCelltypeInfo_skel,
    nTECSInfo_tCellInfo_eCellInfo_getCBP_skel,
    nTECSInfo_tCellInfo_eCellInfo_getINIBP_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_nTECSInfo_sCelltypeInfo_VDES rTEMP_rTECSInfo_tPutStringStdioCelltypeInfo_eCelltypeInfo_des;
extern struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES rTEMP_rTECSInfo_PutStringStdio_ePutStringRawEntryDescriptorInfo_eRawEntryDescriptor_des;

extern struct tag_nTECSInfo_sCelltypeInfo_VDES rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_eCelltypeInfo_des;
extern struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES rTEMP_rTECSInfo_HelloWorld_eMainRawEntryDescriptorInfo_eRawEntryDescriptor_des;

extern struct tag_nTECSInfo_sCelltypeInfo_VDES rTEMP_rTECSInfo_tTaskCelltypeInfo_eCelltypeInfo_des;
extern struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES rTEMP_rTECSInfo_Task_eTaskRawEntryDescriptorInfo_eRawEntryDescriptor_des;

extern struct tag_nTECSInfo_sCelltypeInfo_VDES rTEMP_rTECSInfo_tTaskMainCelltypeInfo_eCelltypeInfo_des;
extern struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES rTEMP_rTECSInfo_rTEMP_TaskMain_eBodyRawEntryDescriptorInfo_eRawEntryDescriptor_des;

extern struct tag_nTECSInfo_sCelltypeInfo_VDES rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_eCelltypeInfo_des;
extern struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES rTEMP_rTECSInfo_rTEMP_TECSInfo_eTECSInfoRawEntryDescriptorInfo_eRawEntryDescriptor_des;

/* call port array #_CPA_# */
struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES * const rTEMP_rTECSInfo_PutStringStdioCellInfo_cRawEntryDescriptor[] = {
    &rTEMP_rTECSInfo_PutStringStdio_ePutStringRawEntryDescriptorInfo_eRawEntryDescriptor_des,
};

struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES * const rTEMP_rTECSInfo_HelloWorldCellInfo_cRawEntryDescriptor[] = {
    &rTEMP_rTECSInfo_HelloWorld_eMainRawEntryDescriptorInfo_eRawEntryDescriptor_des,
};

struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES * const rTEMP_rTECSInfo_TaskCellInfo_cRawEntryDescriptor[] = {
    &rTEMP_rTECSInfo_Task_eTaskRawEntryDescriptorInfo_eRawEntryDescriptor_des,
};

struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES * const rTEMP_rTECSInfo_rTEMP_TaskMainCellInfo_cRawEntryDescriptor[] = {
    &rTEMP_rTECSInfo_rTEMP_TaskMain_eBodyRawEntryDescriptorInfo_eRawEntryDescriptor_des,
};

struct tag_nTECSInfo_sRawEntryDescriptorInfo_VDES * const rTEMP_rTECSInfo_rTEMP_TECSInfoCellInfo_cRawEntryDescriptor[] = {
    &rTEMP_rTECSInfo_rTEMP_TECSInfo_eTECSInfoRawEntryDescriptorInfo_eRawEntryDescriptor_des,
};

/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_nTECSInfo_tCellInfo_CB nTECSInfo_tCellInfo_CB_tab[] = {
    /* cell: nTECSInfo_tCellInfo_CB_tab[0]:  PutStringStdioCellInfo id=1 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_tPutStringStdioCelltypeInfo_eCelltypeInfo_des, /* cCelltypeInfo #_CCP1_# */
        rTEMP_rTECSInfo_PutStringStdioCellInfo_cRawEntryDescriptor, /* #_CCP3B_# */
        1,                                       /* length of cRawEntryDescriptor (n_cRawEntryDescriptor) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "PutStringStdio",                        /* name */
        PutStringStdio__CBP,                     /* cbp */
        PutStringStdio__INIBP,                   /* inibp */
    },
    /* cell: nTECSInfo_tCellInfo_CB_tab[1]:  HelloWorldCellInfo id=2 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_tHelloWorldCelltypeInfo_eCelltypeInfo_des, /* cCelltypeInfo #_CCP1_# */
        rTEMP_rTECSInfo_HelloWorldCellInfo_cRawEntryDescriptor, /* #_CCP3B_# */
        1,                                       /* length of cRawEntryDescriptor (n_cRawEntryDescriptor) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "HelloWorld",                            /* name */
        HelloWorld__CBP,                         /* cbp */
        HelloWorld__INIBP,                       /* inibp */
    },
    /* cell: nTECSInfo_tCellInfo_CB_tab[2]:  TaskCellInfo id=3 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_tTaskCelltypeInfo_eCelltypeInfo_des, /* cCelltypeInfo #_CCP1_# */
        rTEMP_rTECSInfo_TaskCellInfo_cRawEntryDescriptor, /* #_CCP3B_# */
        1,                                       /* length of cRawEntryDescriptor (n_cRawEntryDescriptor) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "Task",                                  /* name */
        Task__CBP,                               /* cbp */
        Task__INIBP,                             /* inibp */
    },
    /* cell: nTECSInfo_tCellInfo_CB_tab[3]:  rTEMP_TaskMainCellInfo id=4 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_tTaskMainCelltypeInfo_eCelltypeInfo_des, /* cCelltypeInfo #_CCP1_# */
        rTEMP_rTECSInfo_rTEMP_TaskMainCellInfo_cRawEntryDescriptor, /* #_CCP3B_# */
        1,                                       /* length of cRawEntryDescriptor (n_cRawEntryDescriptor) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "TaskMain",                              /* name */
        rTEMP_TaskMain__CBP,                     /* cbp */
        rTEMP_TaskMain__INIBP,                   /* inibp */
    },
    /* cell: nTECSInfo_tCellInfo_CB_tab[4]:  rTEMP_TECSInfoCellInfo id=5 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_nTECSInfo_tTECSInfoCelltypeInfo_eCelltypeInfo_des, /* cCelltypeInfo #_CCP1_# */
        rTEMP_rTECSInfo_rTEMP_TECSInfoCellInfo_cRawEntryDescriptor, /* #_CCP3B_# */
        1,                                       /* length of cRawEntryDescriptor (n_cRawEntryDescriptor) #_CCP4_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "TECSInfo",                              /* name */
        rTEMP_TECSInfo__CBP,                     /* cbp */
        rTEMP_TECSInfo__INIBP,                   /* inibp */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_PutStringStdioCellInfo_eCellInfo_des;
const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_PutStringStdioCellInfo_eCellInfo_des = {
    &nTECSInfo_tCellInfo_eCellInfo_MT_,
    &nTECSInfo_tCellInfo_CB_tab[0],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_HelloWorldCellInfo_eCellInfo_des;
const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_HelloWorldCellInfo_eCellInfo_des = {
    &nTECSInfo_tCellInfo_eCellInfo_MT_,
    &nTECSInfo_tCellInfo_CB_tab[1],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_TaskCellInfo_eCellInfo_des;
const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_TaskCellInfo_eCellInfo_des = {
    &nTECSInfo_tCellInfo_eCellInfo_MT_,
    &nTECSInfo_tCellInfo_CB_tab[2],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_rTEMP_TaskMainCellInfo_eCellInfo_des;
const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_rTEMP_TaskMainCellInfo_eCellInfo_des = {
    &nTECSInfo_tCellInfo_eCellInfo_MT_,
    &nTECSInfo_tCellInfo_CB_tab[3],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_rTEMP_TECSInfoCellInfo_eCellInfo_des;
const struct tag_nTECSInfo_tCellInfo_eCellInfo_DES rTEMP_rTECSInfo_rTEMP_TECSInfoCellInfo_eCellInfo_des = {
    &nTECSInfo_tCellInfo_eCellInfo_MT_,
    &nTECSInfo_tCellInfo_CB_tab[4],      /* CB 3 */
};
