/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "nTECSInfo_tEntryInfo_tecsgen.h"
#include "nTECSInfo_tEntryInfo_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntryInfo */
struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES {
    const struct tag_nTECSInfo_sEntryInfo_VMT *vmt;
    tEntryInfo_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eEntryInfo */
ER             nTECSInfo_tEntryInfo_eEntryInfo_getName_skel( const struct tag_nTECSInfo_sEntryInfo_VDES *epd, char_t* name, int_t max_len)
{
    struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *lepd
        = (struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *)epd;
    return nTECSInfo_tEntryInfo_eEntryInfo_getName( lepd->idx, name, max_len );
}
uint16_t       nTECSInfo_tEntryInfo_eEntryInfo_getNameLength_skel( const struct tag_nTECSInfo_sEntryInfo_VDES *epd)
{
    struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *lepd
        = (struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *)epd;
    return nTECSInfo_tEntryInfo_eEntryInfo_getNameLength( lepd->idx );
}
void           nTECSInfo_tEntryInfo_eEntryInfo_getSignatureInfo_skel( const struct tag_nTECSInfo_sEntryInfo_VDES *epd, Descriptor( nTECSInfo_sSignatureInfo )* desc)
{
    struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *lepd
        = (struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *)epd;
    nTECSInfo_tEntryInfo_eEntryInfo_getSignatureInfo( lepd->idx, desc );
}
uint32_t       nTECSInfo_tEntryInfo_eEntryInfo_getArraySize_skel( const struct tag_nTECSInfo_sEntryInfo_VDES *epd)
{
    struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *lepd
        = (struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *)epd;
    return nTECSInfo_tEntryInfo_eEntryInfo_getArraySize( lepd->idx );
}
bool_t         nTECSInfo_tEntryInfo_eEntryInfo_isInline_skel( const struct tag_nTECSInfo_sEntryInfo_VDES *epd)
{
    struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *lepd
        = (struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES *)epd;
    return nTECSInfo_tEntryInfo_eEntryInfo_isInline( lepd->idx );
}

/* entry port skelton function table #_EPSFT_# */
/* eEntryInfo */
const struct tag_nTECSInfo_sEntryInfo_VMT nTECSInfo_tEntryInfo_eEntryInfo_MT_ = {
    nTECSInfo_tEntryInfo_eEntryInfo_getName_skel,
    nTECSInfo_tEntryInfo_eEntryInfo_getNameLength_skel,
    nTECSInfo_tEntryInfo_eEntryInfo_getSignatureInfo_skel,
    nTECSInfo_tEntryInfo_eEntryInfo_getArraySize_skel,
    nTECSInfo_tEntryInfo_eEntryInfo_isInline_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_nTECSInfo_sSignatureInfo_VDES rTEMP_rTECSInfo_sTaskSignatureInfo_eSignatureInfo_des;

extern struct tag_nTECSInfo_sSignatureInfo_VDES rTEMP_rTECSInfo_sPutStringSignatureInfo_eSignatureInfo_des;

extern struct tag_nTECSInfo_sSignatureInfo_VDES rTEMP_rTECSInfo_sTaskBodySignatureInfo_eSignatureInfo_des;

extern struct tag_nTECSInfo_sSignatureInfo_VDES rTEMP_rTECSInfo_sTaskBodySignatureInfo_eSignatureInfo_des;

extern struct tag_nTECSInfo_sSignatureInfo_VDES rTEMP_rTECSInfo_nTECSInfo_sTECSInfoSignatureInfo_eSignatureInfo_des;

/* call port array #_CPA_# */





/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_nTECSInfo_tEntryInfo_CB nTECSInfo_tEntryInfo_CB_tab[] = {
    /* cell: nTECSInfo_tEntryInfo_CB_tab[0]:  tTask_eTaskEntryInfo id=1 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_sTaskSignatureInfo_eSignatureInfo_des, /* cSignatureInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "eTask",                                 /* name */
        true,                                    /* b_inline */
        tTask_eTask__array_size,                 /* array_size */
    },
    /* cell: nTECSInfo_tEntryInfo_CB_tab[1]:  tPutStringStdio_ePutStringEntryInfo id=2 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_sPutStringSignatureInfo_eSignatureInfo_des, /* cSignatureInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "ePutString",                            /* name */
        false,                                   /* b_inline */
        tPutStringStdio_ePutString__array_size,  /* array_size */
    },
    /* cell: nTECSInfo_tEntryInfo_CB_tab[2]:  tHelloWorld_eMainEntryInfo id=3 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_sTaskBodySignatureInfo_eSignatureInfo_des, /* cSignatureInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "eMain",                                 /* name */
        false,                                   /* b_inline */
        tHelloWorld_eMain__array_size,           /* array_size */
    },
    /* cell: nTECSInfo_tEntryInfo_CB_tab[3]:  tTaskMain_eBodyEntryInfo id=4 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_sTaskBodySignatureInfo_eSignatureInfo_des, /* cSignatureInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "eBody",                                 /* name */
        false,                                   /* b_inline */
        tTaskMain_eBody__array_size,             /* array_size */
    },
    /* cell: nTECSInfo_tEntryInfo_CB_tab[4]:  nTECSInfo_tTECSInfo_eTECSInfoEntryInfo id=5 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        &rTEMP_rTECSInfo_nTECSInfo_sTECSInfoSignatureInfo_eSignatureInfo_des, /* cSignatureInfo #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute */ 
        "eTECSInfo",                             /* name */
        true,                                    /* b_inline */
        nTECSInfo_tTECSInfo_eTECSInfo__array_size, /* array_size */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tTask_eTaskEntryInfo_eEntryInfo_des;
const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tTask_eTaskEntryInfo_eEntryInfo_des = {
    &nTECSInfo_tEntryInfo_eEntryInfo_MT_,
    &nTECSInfo_tEntryInfo_CB_tab[0],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tPutStringStdio_ePutStringEntryInfo_eEntryInfo_des;
const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tPutStringStdio_ePutStringEntryInfo_eEntryInfo_des = {
    &nTECSInfo_tEntryInfo_eEntryInfo_MT_,
    &nTECSInfo_tEntryInfo_CB_tab[1],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tHelloWorld_eMainEntryInfo_eEntryInfo_des;
const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tHelloWorld_eMainEntryInfo_eEntryInfo_des = {
    &nTECSInfo_tEntryInfo_eEntryInfo_MT_,
    &nTECSInfo_tEntryInfo_CB_tab[2],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tTaskMain_eBodyEntryInfo_eEntryInfo_des;
const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_tTaskMain_eBodyEntryInfo_eEntryInfo_des = {
    &nTECSInfo_tEntryInfo_eEntryInfo_MT_,
    &nTECSInfo_tEntryInfo_CB_tab[3],      /* CB 3 */
};
extern const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_nTECSInfo_tTECSInfo_eTECSInfoEntryInfo_eEntryInfo_des;
const struct tag_nTECSInfo_tEntryInfo_eEntryInfo_DES rTEMP_rTECSInfo_nTECSInfo_tTECSInfo_eTECSInfoEntryInfo_eEntryInfo_des = {
    &nTECSInfo_tEntryInfo_eEntryInfo_MT_,
    &nTECSInfo_tEntryInfo_CB_tab[4],      /* CB 3 */
};
