/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tAttribute4_tecsgen.h"
#include "tAttribute4_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tAttribute4_INIB tAttribute4_INIB_tab[] = {
    /* cell: tAttribute4_CB_tab[0]:  Attr4 id=1 */
    {
        /* attribute(RO) */ 
        {
            0,                                       /* buf0[0] */
            0,                                       /* buf0[1] */
        },
    },
};

/* entry port descriptor #_EPD_# */
/* CB initialize code #_CIC_# */
void
tAttribute4_CB_initialize()
{
    tAttribute4_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
