/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCelltype_tecsgen.h"
#include "tCelltype_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
const char_t* tCelltype_Cell_CB_array_INIT[3] = { "A", "B", "C", };
/* cell INIB #_INIB_# */
tCelltype_INIB tCelltype_INIB_tab[] = {
    /* cell: tCelltype_CB_tab[0]:  Cell id=1 */
    {
        /* attribute(RO) */ 
        tCelltype_Cell_CB_array_INIT,            /* array */
        3,                                       /* size */
    },
};

/* entry port descriptor #_EPD_# */
/* CB initialize code #_CIC_# */
void
tCelltype_CB_initialize()
{
    tCelltype_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
