/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tMain_TECSGEN_H
#define tMain_TECSGEN_H

/*
 * celltype          :  tMain
 * global name       :  tMain
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  yes
 * has_CB            :  yes
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sMain_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tMain_INIB {
    /* call port #_TCP_# */
    struct tag_sMain_VDES *const*cMain; /* TCP_2 */
    int_t n_cMain;  /* TCP_3 */
    /* attribute(RO) #_ATO_# */ 
    int32_t        a;
}  tMain_INIB;
/* cell CB type definition #_CCTPA_# */
typedef struct tag_tMain_CB {
    tMain_INIB  *_inib;
    /* call port #_TCP_# */
    /* var #_VA_# */ 
    int32_t        v;
}  tMain_CB;
/* singleton cell CB prototype declaration #_SCP_# */
extern  tMain_CB  tMain_SINGLE_CELL_CB;
extern  tMain_INIB  tMain_SINGLE_CELL_INIB;


/* celltype IDX type #_CTIX_# */
typedef struct tag_tMain_CB *tMain_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* call port array size macro #_NCPA_# */
#define N_CP_cMain  (tMain_SINGLE_CELL_INIB.n_cMain)
#define NCP_cMain   (tMain_SINGLE_CELL_INIB.n_cMain)

/* celll CB macro #_GCB_# */
#define tMain_GET_CELLCB(idx) ((void *)0)

/* attr access  #_AAM_# */
#define tMain_ATTR_a        	(tMain_SINGLE_CELL_INIB.a)

#define tMain_GET_a()       	(tMain_SINGLE_CELL_INIB.a)


/* var access macro #_VAM_# */
#define tMain_VAR_v         	(tMain_SINGLE_CELL_CB.v)

#define tMain_GET_v()       	(tMain_SINGLE_CELL_CB.v)
#define tMain_SET_v(val)    	(tMain_SINGLE_CELL_CB.v=(val))

#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tMain_cMain_main( subscript ) \
	  tMain_SINGLE_CELL_INIB.cMain[subscript]->VMT->main__T( \
	  tMain_SINGLE_CELL_INIB.cMain[subscript] )

#else  /* TECSFLOW */
#define tMain_cMain_main( subscript ) \
	  (p_that)->cMain[subscript].main__T( \
 )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tMain_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tMain_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tMain_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_a               tMain_ATTR_a


/* var access macro (abbrev) #_VAMA_# */
#define VAR_v                tMain_VAR_v

/* call port function macro (abbrev) #_CPMA_# */
#define cMain_main( subscript ) \
          tMain_cMain_main( subscript )



/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB()\
	tMain_SINGLE_CELL_CB.v = tMain_ATTR_a;
#define SET_CB_INIB_POINTER(i,p_that)\
	tMain_SINGLE_CELL_CB._inib = &tMain_SINGLE_CELL_INIB;

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tMain_TECSGENH */
