/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCell4_tecsgen.h"
#include "tCell4_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntry4 : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eEntry4 : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eEntry4 : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
/* cell: comp1_comp12_cell4_CB:  comp1_comp12_cell4 id=7 */
const tCell4_INIB comp1_comp12_cell4_INIB = {
    /* entry port #_EP_# */ 
    /* attribute(RO) */ 
    101,                                     /* a */
};

/* cell: comp2_comp12_cell4_CB:  comp2_comp12_cell4 id=8 */
const tCell4_INIB comp2_comp12_cell4_INIB = {
    /* entry port #_EP_# */ 
    /* attribute(RO) */ 
    10,                                      /* a */
};

/* entry port descriptor #_EPD_# */
/* eEntry4 : omitted by entry port optimize */
/* eEntry4 : omitted by entry port optimize */
/* ID to INIB table #_INTAB_# */
tCell4_INIB *const tCell4_INIB_ptab[] ={
    &comp1_comp12_cell4_INIB,
    &comp2_comp12_cell4_INIB,
};
