/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tCell_clnt_templ.c => src/tCell_clnt.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * a                int32_t          ATTR_a          
 *
 * call port function #_TCPF_#
 * call port: cCall signature: sSig1 context:task
 *   int32_t        cCall_func1( subscript, int32_t a );
 *   int32_t        cCall_func2( subscript, int32_t a );
 *       subscript:  0...(NCP_cCall-1)
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tCell_clnt_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
