/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tCelltype_TECSGEN_H
#define tCelltype_TECSGEN_H

/*
 * celltype          :  tCelltype
 * global name       :  tCelltype
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  no
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tCelltype_INIB {
    /* attribute(RO) #_ATO_# */ 
    const char_t**       array;
    int            size;
}  tCelltype_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tCelltype_CB_tab           tCelltype_INIB_tab
#define tCelltype_CB               tCelltype_INIB
#define tag_tCelltype_CB           tag_tCelltype_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tCelltype_INIB  tCelltype_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tCelltype_INIB *tCelltype_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tCelltype_ID_BASE           (1)  /* ID Base  #_NIDB_# */
#define tCelltype_N_CELL            (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tCelltype_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tCelltype_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tCelltype_ATTR_array( p_that )	((p_that)->array)
#define tCelltype_ATTR_size( p_that )	((p_that)->size)

#define tCelltype_GET_array(p_that)	((p_that)->array)
#define tCelltype_GET_size(p_that)	((p_that)->size)



#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tCelltype_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tCelltype_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tCelltype_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tCelltype_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_array           tCelltype_ATTR_array( p_cellcb )
#define ATTR_size            tCelltype_ATTR_size( p_cellcb )




/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tCelltype_N_CELL; (i)++ ){ \
       //(p_cb) = &tCelltype_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tCelltype_TECSGENH */
