/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tMainArray_tecsgen.h"
#include "tMainArray_factory.h"

/* entry port descriptor type #_EDT_# */
/* eMain */
struct tag_tMainArray_eMain_DES {
    const struct tag_sTaskBody_VMT *vmt;
    tMainArray_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eMain */
void           tMainArray_eMain_main_skel( const struct tag_sTaskBody_VDES *epd)
{
    struct tag_tMainArray_eMain_DES *lepd
        = (struct tag_tMainArray_eMain_DES *)epd;
    tMainArray_eMain_main( lepd->idx );
}

/* entry port skelton function table #_EPSFT_# */
/* eMain */
const struct tag_sTaskBody_VMT tMainArray_eMain_MT_ = {
    tMainArray_eMain_main_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_sHello_VDES Talker0_eHello_des;
extern struct tag_sHello_VDES Talker0_eHello_des;
extern struct tag_sHello_VDES Talker1_eHello_des;
extern struct tag_sHello_VDES Talker2_eHello_des;
extern struct tag_sTalkerSelector_VDES Selector_eTalkerSelector_des;

extern struct tag_sHello_VDES rComposite_Talker0_eHello_des;
extern struct tag_sHello_VDES rComposite_Talker0_eHello_des;
extern struct tag_sHello_VDES rComposite_Talker1_eHello_des;
extern struct tag_sHello_VDES rComposite_Talker2_eHello_des;
extern struct tag_sTalkerSelector_VDES rComposite_Selector_eTalkerSelector_des;

/* call port array #_CPA_# */
struct tag_sHello_VDES * Main_cTalker[] = {
    &Talker0_eHello_des,
    &Talker1_eHello_des,
    &Talker2_eHello_des,
};
struct tag_sHello_VDES * Main_cTalker2[] = {
    0,
    0,
};

struct tag_sHello_VDES * rComposite_CompMain_Main_cTalker[] = {
    &rComposite_Talker0_eHello_des,
    &rComposite_Talker1_eHello_des,
    &rComposite_Talker2_eHello_des,
};
struct tag_sHello_VDES * rComposite_CompMain_Main_cTalker2[] = {
    0,
    0,
};

/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tMainArray_INIB tMainArray_INIB_tab[] = {
    /* cell: tMainArray_CB_tab[0]:  Main id=1 */
    {
        /* call port (INIB) #_CP_# */ 
        &Talker0_eHello_des,                     /* cDefaultTalker #_CCP1_# */
        Main_cTalker,                            /* #_CCP3B_# */
        3,                                       /* length of cTalker (n_cTalker) #_CCP4_# */
        Main_cTalker2,                           /* #_CCP7B_# */
        &tTalkerSelector_INIB_tab[0],            /* cTalkerSelector #_CCP2_# */
        /* entry port #_EP_# */ 
    },
    /* cell: tMainArray_CB_tab[1]:  CompMain_Main id=2 */
    {
        /* call port (INIB) #_CP_# */ 
        &rComposite_Talker0_eHello_des,          /* cDefaultTalker #_CCP1_# */
        rComposite_CompMain_Main_cTalker,        /* #_CCP3B_# */
        3,                                       /* length of cTalker (n_cTalker) #_CCP4_# */
        rComposite_CompMain_Main_cTalker2,       /* #_CCP7B_# */
        &tTalkerSelector_INIB_tab[1],            /* cTalkerSelector #_CCP2_# */
        /* entry port #_EP_# */ 
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tMainArray_eMain_DES Main_eMain_des;
const struct tag_tMainArray_eMain_DES Main_eMain_des = {
    &tMainArray_eMain_MT_,
    &tMainArray_INIB_tab[0],      /* INIB 3 */
};
extern const struct tag_tMainArray_eMain_DES rComposite_CompMain_Main_eMain_des;
const struct tag_tMainArray_eMain_DES rComposite_CompMain_Main_eMain_des = {
    &tMainArray_eMain_MT_,
    &tMainArray_INIB_tab[1],      /* INIB 3 */
};
