/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCPArray_tecsgen.h"
#include "tCPArray_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEnt */
struct tag_tCPArray_eEnt_DES {
    const struct tag_sSig_VMT *vmt;
    tCPArray_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eEnt */
void           tCPArray_eEnt_func_skel( const struct tag_sSig_VDES *epd)
{
    struct tag_tCPArray_eEnt_DES *lepd
        = (struct tag_tCPArray_eEnt_DES *)epd;
    tCPArray_eEnt_func( lepd->idx );
}
int32_t        tCPArray_eEnt_func2_skel( const struct tag_sSig_VDES *epd, int32_t arg)
{
    struct tag_tCPArray_eEnt_DES *lepd
        = (struct tag_tCPArray_eEnt_DES *)epd;
    return tCPArray_eEnt_func2( lepd->idx, arg );
}
struct tagST   tCPArray_eEnt_func3_skel( const struct tag_sSig_VDES *epd, struct tagST a)
{
    struct tag_tCPArray_eEnt_DES *lepd
        = (struct tag_tCPArray_eEnt_DES *)epd;
    return tCPArray_eEnt_func3( lepd->idx, a );
}

/* entry port skelton function table #_EPSFT_# */
/* eEnt */
const struct tag_sSig_VMT tCPArray_eEnt_MT_ = {
    tCPArray_eEnt_func_skel,
    tCPArray_eEnt_func2_skel,
    tCPArray_eEnt_func3_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

extern struct tag_sSig_VDES SingleCellOptimizeCaller_eEnt_des;
extern struct tag_sSig_VDES VMTUselessOptimizeCaller_eEnt_des;

extern struct tag_sSig_VDES VMTUselessOptimizeCaller_eEnt_des;


/* call port array #_CPA_# */
struct tag_sSig_VDES * const CPArray1_cCall[] = {
    0,
    0,
    0,
};

struct tag_sSig_VDES * const CPArray2_cCall[] = {
    &SingleCellOptimizeCaller_eEnt_des,
    &VMTUselessOptimizeCaller_eEnt_des,
    0,
};

struct tag_sSig_VDES * const CPArray3_cCall[] = {
    0,
    0,
    &VMTUselessOptimizeCaller_eEnt_des,
};

struct tag_sSig_VDES * const Comp_CPArray_cCall[] = {
    0,
    0,
    0,
};

/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_tCPArray_CB tCPArray_CB_tab[] = {
    /* cell: tCPArray_CB_tab[0]:  CPArray1 id=1 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        0,                                       /* #_CCP9_# */
        /* entry port #_EP_# */ 
    },
    /* cell: tCPArray_CB_tab[1]:  CPArray2 id=2 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        CPArray2_cCall,                          /* #_CCP3B_# */
        /* entry port #_EP_# */ 
    },
    /* cell: tCPArray_CB_tab[2]:  CPArray3 id=3 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        CPArray3_cCall,                          /* #_CCP3B_# */
        /* entry port #_EP_# */ 
    },
    /* cell: tCPArray_CB_tab[3]:  Comp_CPArray id=4 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        0,                                       /* #_CCP9_# */
        /* entry port #_EP_# */ 
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tCPArray_eEnt_DES CPArray1_eEnt_des;
const struct tag_tCPArray_eEnt_DES CPArray1_eEnt_des = {
    &tCPArray_eEnt_MT_,
    &tCPArray_CB_tab[0],      /* CB 3 */
};
extern const struct tag_tCPArray_eEnt_DES CPArray2_eEnt_des;
const struct tag_tCPArray_eEnt_DES CPArray2_eEnt_des = {
    &tCPArray_eEnt_MT_,
    &tCPArray_CB_tab[1],      /* CB 3 */
};
extern const struct tag_tCPArray_eEnt_DES CPArray3_eEnt_des;
const struct tag_tCPArray_eEnt_DES CPArray3_eEnt_des = {
    &tCPArray_eEnt_MT_,
    &tCPArray_CB_tab[2],      /* CB 3 */
};
extern const struct tag_tCPArray_eEnt_DES Comp_CPArray_eEnt_des;
const struct tag_tCPArray_eEnt_DES Comp_CPArray_eEnt_des = {
    &tCPArray_eEnt_MT_,
    &tCPArray_CB_tab[3],      /* CB 3 */
};
