/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tSingleCellOptimizeCaller_tecsgen.h"
#include "tSingleCellOptimizeCaller_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEnt */
struct tag_tSingleCellOptimizeCaller_eEnt_DES {
    const struct tag_sSig_VMT *vmt;
    tSingleCellOptimizeCaller_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eEnt */
void           tSingleCellOptimizeCaller_eEnt_func_skel( const struct tag_sSig_VDES *epd)
{
    struct tag_tSingleCellOptimizeCaller_eEnt_DES *lepd
        = (struct tag_tSingleCellOptimizeCaller_eEnt_DES *)epd;
    tSingleCellOptimizeCaller_eEnt_func( lepd->idx );
}
int32_t        tSingleCellOptimizeCaller_eEnt_func2_skel( const struct tag_sSig_VDES *epd, int32_t arg)
{
    struct tag_tSingleCellOptimizeCaller_eEnt_DES *lepd
        = (struct tag_tSingleCellOptimizeCaller_eEnt_DES *)epd;
    return tSingleCellOptimizeCaller_eEnt_func2( lepd->idx, arg );
}
struct tagST   tSingleCellOptimizeCaller_eEnt_func3_skel( const struct tag_sSig_VDES *epd, struct tagST a)
{
    struct tag_tSingleCellOptimizeCaller_eEnt_DES *lepd
        = (struct tag_tSingleCellOptimizeCaller_eEnt_DES *)epd;
    return tSingleCellOptimizeCaller_eEnt_func3( lepd->idx, a );
}

/* entry port skelton function table #_EPSFT_# */
/* eEnt */
const struct tag_sSig_VMT tSingleCellOptimizeCaller_eEnt_MT_ = {
    tSingleCellOptimizeCaller_eEnt_func_skel,
    tSingleCellOptimizeCaller_eEnt_func2_skel,
    tSingleCellOptimizeCaller_eEnt_func3_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell CB #_CB_# */
struct tag_tSingleCellOptimizeCaller_CB tSingleCellOptimizeCaller_CB_tab[] = {
    /* cell: tSingleCellOptimizeCaller_CB_tab[0]:  SingleCellOptimizeCaller id=1 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cWhite (n_cWhite) #_CCP6_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cBlack (n_cBlack) #_CCP6_# */
        /* entry port #_EP_# */ 
    },
    /* cell: tSingleCellOptimizeCaller_CB_tab[1]:  SingleCellOptimizeCaller2 id=2 */
    {
        /* call port (CB_ALL) #_CP_# */ 
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cWhite (n_cWhite) #_CCP6_# */
        0,                                       /* #_CCP9_# */
        0,                                       /* length of cBlack (n_cBlack) #_CCP6_# */
        /* entry port #_EP_# */ 
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tSingleCellOptimizeCaller_eEnt_DES SingleCellOptimizeCaller_eEnt_des;
const struct tag_tSingleCellOptimizeCaller_eEnt_DES SingleCellOptimizeCaller_eEnt_des = {
    &tSingleCellOptimizeCaller_eEnt_MT_,
    &tSingleCellOptimizeCaller_CB_tab[0],      /* CB 3 */
};
extern const struct tag_tSingleCellOptimizeCaller_eEnt_DES SingleCellOptimizeCaller2_eEnt_des;
const struct tag_tSingleCellOptimizeCaller_eEnt_DES SingleCellOptimizeCaller2_eEnt_des = {
    &tSingleCellOptimizeCaller_eEnt_MT_,
    &tSingleCellOptimizeCaller_CB_tab[1],      /* CB 3 */
};
