/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tVMTUselessOptimizeCaller_TECSGEN_H
#define tVMTUselessOptimizeCaller_TECSGEN_H

/*
 * celltype          :  tVMTUselessOptimizeCaller
 * global name       :  tVMTUselessOptimizeCaller
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sSig_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tVMTUselessOptimizeCaller_CB {
    /* call port #_TCP_# */
    struct tag_sSig_VDES const*cCall; /* TCP_2 */
    /* call port #_NEP_# */ 
}  tVMTUselessOptimizeCaller_CB;
/* singleton cell CB prototype declaration #_MCPB_# */
extern tVMTUselessOptimizeCaller_CB  tVMTUselessOptimizeCaller_CB_tab[];

/* celltype IDX type #_CTIX_# */
typedef struct tag_tVMTUselessOptimizeCaller_CB *tVMTUselessOptimizeCaller_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sSig */
void         tVMTUselessOptimizeCaller_eEnt_func(tVMTUselessOptimizeCaller_IDX idx);
int32_t      tVMTUselessOptimizeCaller_eEnt_func2(tVMTUselessOptimizeCaller_IDX idx, int32_t arg);
struct tagST tVMTUselessOptimizeCaller_eEnt_func3(tVMTUselessOptimizeCaller_IDX idx, struct tagST a);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tVMTUselessOptimizeCaller_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tVMTUselessOptimizeCallee_tecsgen.h"
#ifdef  tVMTUselessOptimizeCaller_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tVMTUselessOptimizeCaller_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tVMTUselessOptimizeCaller_ID_BASE        (1)  /* ID Base  #_NIDB_# */
#define tVMTUselessOptimizeCaller_N_CELL        (2)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tVMTUselessOptimizeCaller_VALID_IDX(IDX) (1)

/* optional call port test macro #_TOCP_# */
#define tVMTUselessOptimizeCaller_is_cCall_joined(p_that) \
	  (1)

/* celll CB macro #_GCB_# */
#define tVMTUselessOptimizeCaller_GET_CELLCB(idx) (idx)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tVMTUselessOptimizeCaller_cCall_func( p_that ) \
	  tVMTUselessOptimizeCallee_eEnt_func_skel( \
	   (p_that)->cCall )
#define tVMTUselessOptimizeCaller_cCall_func2( p_that, arg ) \
	  tVMTUselessOptimizeCallee_eEnt_func2_skel( \
	   (p_that)->cCall, (arg) )
#define tVMTUselessOptimizeCaller_cCall_func3( p_that, a ) \
	  tVMTUselessOptimizeCallee_eEnt_func3_skel( \
	   (p_that)->cCall, (a) )

#else  /* TECSFLOW */
#define tVMTUselessOptimizeCaller_cCall_func( p_that ) \
	  (p_that)->cCall.func__T( \
 )
#define tVMTUselessOptimizeCaller_cCall_func2( p_that, arg ) \
	  (p_that)->cCall.func2__T( \
 (arg) )
#define tVMTUselessOptimizeCaller_cCall_func3( p_that, a ) \
	  (p_that)->cCall.func3__T( \
 (a) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eEnt */
void           tVMTUselessOptimizeCaller_eEnt_func_skel( const struct tag_sSig_VDES *epd);
int32_t        tVMTUselessOptimizeCaller_eEnt_func2_skel( const struct tag_sSig_VDES *epd, int32_t arg);
struct tagST   tVMTUselessOptimizeCaller_eEnt_func3_skel( const struct tag_sSig_VDES *epd, struct tagST a);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tVMTUselessOptimizeCaller_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tVMTUselessOptimizeCaller_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tVMTUselessOptimizeCaller_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tVMTUselessOptimizeCaller_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cCall_func( ) \
          ((void)p_cellcb, tVMTUselessOptimizeCaller_cCall_func( p_cellcb ))
#define cCall_func2( arg ) \
          ((void)p_cellcb, tVMTUselessOptimizeCaller_cCall_func2( p_cellcb, arg ))
#define cCall_func3( a ) \
          ((void)p_cellcb, tVMTUselessOptimizeCaller_cCall_func3( p_cellcb, a ))



/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cCall_joined()\
		tVMTUselessOptimizeCaller_is_cCall_joined(p_cellcb)

/* entry port function macro (abbrev) #_EPM_# */
#define eEnt_func        tVMTUselessOptimizeCaller_eEnt_func
#define eEnt_func2       tVMTUselessOptimizeCaller_eEnt_func2
#define eEnt_func3       tVMTUselessOptimizeCaller_eEnt_func3

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tVMTUselessOptimizeCaller_N_CELL; (i)++ ){ \
       (p_cb) = &tVMTUselessOptimizeCaller_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tVMTUselessOptimizeCaller_TECSGENH */
