/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tMain_TECSGEN_H
#define tMain_TECSGEN_H

/*
 * celltype          :  tMain
 * global name       :  tMain
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sTaskBody_tecsgen.h"
#include "sHello_tecsgen.h"
#include "sTalkerSelector_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tMain_CB {
    /* call port #_TCP_# */
    struct tag_sHello_VDES const*cDefaultTalker; /* TCP_2 */
    struct tag_sHello_VDES *cTalker; /* TCP_2 */
    /* call port #_NEP_# */ 
}  tMain_CB;
/* singleton cell CB prototype declaration #_MCPB_# */
extern tMain_CB  tMain_CB_tab[];

/* celltype IDX type #_CTIX_# */
typedef struct tag_tMain_CB *tMain_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sTaskBody */
void         tMain_eMain_main(tMain_IDX idx);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tMain_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tTalkerSelector_tecsgen.h"
#ifdef  tMain_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tMain_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tMain_ID_BASE               (1)  /* ID Base  #_NIDB_# */
#define tMain_N_CELL                (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tMain_VALID_IDX(IDX) (1)

/* optional call port test macro #_TOCP_# */
#define tMain_is_cTalker_joined(p_that) \
	  ((p_that)->cTalker!=0)

/* celll CB macro #_GCB_# */
#define tMain_GET_CELLCB(idx) (idx)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tMain_cDefaultTalker_hello( p_that ) \
	  (p_that)->cDefaultTalker->VMT->hello__T( \
	   (p_that)->cDefaultTalker )
#define tMain_cTalker_hello( p_that ) \
	  (p_that)->cTalker->VMT->hello__T( \
	   (p_that)->cTalker )
#define tMain_cTalkerSelector_getTalker( p_that, talker, i ) \
	  tTalkerSelector_eTalkerSelector_getTalker( \
	   &tTalkerSelector_CB_tab[0], (talker), (i) )
#define tMain_cTalkerSelector_getNTalker( p_that, n ) \
	  tTalkerSelector_eTalkerSelector_getNTalker( \
	   &tTalkerSelector_CB_tab[0], (n) )

#else  /* TECSFLOW */
#define tMain_cDefaultTalker_hello( p_that ) \
	  (p_that)->cDefaultTalker.hello__T( \
 )
#define tMain_cTalker_hello( p_that ) \
	  (p_that)->cTalker.hello__T( \
 )
#define tMain_cTalkerSelector_getTalker( p_that, talker, i ) \
	  (p_that)->cTalkerSelector.getTalker__T( \
 (talker), (i) )
#define tMain_cTalkerSelector_getNTalker( p_that, n ) \
	  (p_that)->cTalkerSelector.getNTalker__T( \
 (n) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
void           tMain_eMain_main_skel( const struct tag_sTaskBody_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

/* refer to descriptor function #_CRD_# */
/* [ref_desc] cDefaultTalker */
Inline Descriptor( sHello )
tMain_cDefaultTalker_refer_to_descriptor( tMain_CB  *p_that )
{
    Descriptor( sHello )  des;
    tMain_CB *p_cellcb = p_that;
    /* cast is ncecessary for removing 'const'  */
    des.vdes = (struct tag_sHello_VDES *)p_cellcb->cDefaultTalker;
    return des;
}

/* set descriptor function #_SDF_# */
/* [dynamic] cTalker */
Inline void
tMain_cTalker_set_descriptor( tMain_CB  *p_that, Descriptor( sHello ) des )
{
    tMain_CB *p_cellcb = p_that;
    assert( des.vdes != NULL );
    (p_cellcb)->cTalker = des.vdes;
}

/* [dynamic,optional] cTalker */
Inline void
tMain_cTalker_unjoin( tMain_CB  *p_that  )
{
    tMain_CB *p_cellcb = p_that;
    (p_cellcb)->cTalker = NULL;
}

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tMain_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tMain_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tMain_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tMain_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cDefaultTalker_hello( ) \
          tMain_cDefaultTalker_hello( p_cellcb )
#define cTalker_hello( ) \
          tMain_cTalker_hello( p_cellcb )
#define cTalkerSelector_getTalker( talker, i ) \
          ((void)p_cellcb, tMain_cTalkerSelector_getTalker( p_cellcb, talker, i ))
#define cTalkerSelector_getNTalker( n ) \
          ((void)p_cellcb, tMain_cTalkerSelector_getNTalker( p_cellcb, n ))


/* refer to descriptor macro (abbrev) #_CRDA_# */
#define cDefaultTalker_refer_to_descriptor()\
          tMain_cDefaultTalker_refer_to_descriptor( p_cellcb )
#define cDefaultTalker_ref_desc()\
          cDefaultTalker_refer_to_descriptor()


/* set descriptor macro (abbrev) #_SDMA_# */
#define cTalker_set_descriptor( desc )\
          tMain_cTalker_set_descriptor( p_cellcb, desc )
#define cTalker_unjoin(  )\
          tMain_cTalker_unjoin( p_cellcb )

/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cTalker_joined()\
		tMain_is_cTalker_joined(p_cellcb)

/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tMain_eMain_main

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tMain_N_CELL; (i)++ ){ \
       (p_cb) = &tMain_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tMain_TECSGENH */
