/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCell2_tecsgen.h"
#include "tCell2_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntry2 : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eEntry2 : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eEntry2 : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_sSig3_VDES comp1_comp12_cell3_eEntry3_des;

extern struct tag_sSig3_VDES comp2_comp12_cell3_eEntry3_des;

/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tCell2_INIB tCell2_INIB_tab[] = {
    /* cell: tCell2_CB_tab[0]:  comp1_comp11_cell2 id=1 */
    {
        /* call port (INIB) #_CP_# */ 
        &tCell3_INIB_tab[0],                     /* cCall2 #_CCP2_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        20,                                      /* a */
    },
    /* cell: tCell2_CB_tab[1]:  comp2_comp11_cell2 id=2 */
    {
        /* call port (INIB) #_CP_# */ 
        &tCell3_INIB_tab[1],                     /* cCall2 #_CCP2_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        20,                                      /* a */
    },
};

/* entry port descriptor #_EPD_# */
/* eEntry2 : omitted by entry port optimize */
/* eEntry2 : omitted by entry port optimize */
