/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tMainSingletonForComp_TECSGEN_H
#define tMainSingletonForComp_TECSGEN_H

/*
 * celltype          :  tMainSingletonForComp
 * global name       :  tMainSingletonForComp
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  yes
 * has_CB            :  yes
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sTaskBody_tecsgen.h"
#include "sHello_tecsgen.h"
#include "sTalkerSelector_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tMainSingletonForComp_INIB {
    /* call port #_TCP_# */
    struct tag_sHello_VDES const*cDefaultTalker; /* TCP_2 */
    /* call port #_NEP_# */ 
}  tMainSingletonForComp_INIB;
/* cell CB type definition #_CCTPA_# */
typedef struct tag_tMainSingletonForComp_CB {
    tMainSingletonForComp_INIB  *_inib;
    /* call port #_TCP_# */
    struct tag_sHello_VDES *cTalker; /* TCP_2 */
    /* call port #_NEP_# */ 
}  tMainSingletonForComp_CB;
/* singleton cell CB prototype declaration #_SCP_# */
extern  tMainSingletonForComp_CB  tMainSingletonForComp_SINGLE_CELL_CB;
extern  tMainSingletonForComp_INIB  tMainSingletonForComp_SINGLE_CELL_INIB;


/* celltype IDX type #_CTIX_# */
typedef struct tag_tMainSingletonForComp_CB *tMainSingletonForComp_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sTaskBody */
void         tMainSingletonForComp_eMain_main();
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tMainSingletonForComp_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tTalkerSelector_tecsgen.h"
#ifdef  tMainSingletonForComp_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tMainSingletonForComp_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

/* optional call port test macro #_TOCP_# */
#define tMainSingletonForComp_is_cTalker_joined() \
	  (tMainSingletonForComp_SINGLE_CELL_CB.cTalker!=0)

/* celll CB macro #_GCB_# */
#define tMainSingletonForComp_GET_CELLCB(idx) ((void *)0)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tMainSingletonForComp_cDefaultTalker_hello( ) \
	  tMainSingletonForComp_SINGLE_CELL_INIB.cDefaultTalker->VMT->hello__T( \
	  tMainSingletonForComp_SINGLE_CELL_INIB.cDefaultTalker )
#define tMainSingletonForComp_cTalker_hello( ) \
	  tMainSingletonForComp_SINGLE_CELL_CB.cTalker->VMT->hello__T( \
	  tMainSingletonForComp_SINGLE_CELL_CB.cTalker )
#define tMainSingletonForComp_cTalkerSelector_getTalker( talker, i ) \
	  tTalkerSelector_eTalkerSelector_getTalker( \
	   &tTalkerSelector_INIB_tab[1], (talker), (i) )
#define tMainSingletonForComp_cTalkerSelector_getNTalker( n ) \
	  tTalkerSelector_eTalkerSelector_getNTalker( \
	   &tTalkerSelector_INIB_tab[1], (n) )

#else  /* TECSFLOW */
#define tMainSingletonForComp_cDefaultTalker_hello( ) \
	  (p_that)->cDefaultTalker.hello__T( \
 )
#define tMainSingletonForComp_cTalker_hello( ) \
	  (p_that)->cTalker.hello__T( \
 )
#define tMainSingletonForComp_cTalkerSelector_getTalker( talker, i ) \
	  (p_that)->cTalkerSelector.getTalker__T( \
 (talker), (i) )
#define tMainSingletonForComp_cTalkerSelector_getNTalker( n ) \
	  (p_that)->cTalkerSelector.getNTalker__T( \
 (n) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
void           tMainSingletonForComp_eMain_main_skel( const struct tag_sTaskBody_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

/* refer to descriptor function #_CRD_# */
/* [ref_desc] cDefaultTalker */
Inline Descriptor( sHello )
tMainSingletonForComp_cDefaultTalker_refer_to_descriptor(  )
{
    Descriptor( sHello )  des;
    /* cast is ncecessary for removing 'const'  */
    des.vdes = (struct tag_sHello_VDES *)tMainSingletonForComp_SINGLE_CELL_INIB.cDefaultTalker;
    return des;
}

/* set descriptor function #_SDF_# */
/* [dynamic] cTalker */
Inline void
tMainSingletonForComp_cTalker_set_descriptor( Descriptor( sHello ) des )
{
    assert( des.vdes != NULL );
    tMainSingletonForComp_SINGLE_CELL_CB.cTalker = des.vdes;
}

/* [dynamic,optional] cTalker */
Inline void
tMainSingletonForComp_cTalker_unjoin(  )
{
    tMainSingletonForComp_SINGLE_CELL_CB.cTalker = NULL;
}

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tMainSingletonForComp_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tMainSingletonForComp_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tMainSingletonForComp_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cDefaultTalker_hello( ) \
          tMainSingletonForComp_cDefaultTalker_hello( )
#define cTalker_hello( ) \
          tMainSingletonForComp_cTalker_hello( )
#define cTalkerSelector_getTalker( talker, i ) \
          tMainSingletonForComp_cTalkerSelector_getTalker( talker, i )
#define cTalkerSelector_getNTalker( n ) \
          tMainSingletonForComp_cTalkerSelector_getNTalker( n )


/* refer to descriptor macro (abbrev) #_CRDA_# */
#define cDefaultTalker_refer_to_descriptor()\
          tMainSingletonForComp_cDefaultTalker_refer_to_descriptor(  )
#define cDefaultTalker_ref_desc()\
          cDefaultTalker_refer_to_descriptor()


/* set descriptor macro (abbrev) #_SDMA_# */
#define cTalker_set_descriptor( desc )\
          tMainSingletonForComp_cTalker_set_descriptor( desc )
#define cTalker_unjoin(  )\
          tMainSingletonForComp_cTalker_unjoin(  )

/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cTalker_joined()\
		tMainSingletonForComp_is_cTalker_joined()

/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tMainSingletonForComp_eMain_main

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB()
#define SET_CB_INIB_POINTER(i,p_that)\
	tMainSingletonForComp_SINGLE_CELL_CB._inib = &tMainSingletonForComp_SINGLE_CELL_INIB;

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tMainSingletonForComp_TECSGENH */
