/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCt2_tecsgen.h"
#include "tCt2_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
/* cell: ct2_CB:  ct2 id=3 */
const tCt2_INIB ct2_INIB = {
    /* attribute(RO) */ 
    20,                                      /* a */
};

/* cell CB #_CB_# */
/* cell: ct2_CB:  ct2 id=3 */
tCt2_CB ct2_CB = {};
/* entry port descriptor #_EPD_# */
/* ID to INIB table #_INTAB_# */
tCt2_INIB *const tCt2_INIB_ptab[] ={
    &ct2_INIB,
};
/* ID to CB table #_CBTAB_# */
tCt2_CB *const tCt2_CB_ptab[] ={
    &ct2_CB,
};
/* CB initialize code #_CIC_# */
void
tCt2_CB_initialize()
{
    tCt2_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
