/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tSCt_no_CB_a_INIB_TECSGEN_H
#define tSCt_no_CB_a_INIB_TECSGEN_H

/*
 * celltype          :  tSCt_no_CB_a_INIB
 * global name       :  tSCt_no_CB_a_INIB
 * multi-domain      :  no
 * idx_is_id(actual) :  yes(no)
 * singleton         :  yes
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tSCt_no_CB_a_INIB_INIB {
    /* attribute(RO) #_ATO_# */ 
    int32_t        size;
    int8_t*        buf;
}  tSCt_no_CB_a_INIB_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tSCt_no_CB_a_INIB_SINGLE_CELL_CB   tSCt_no_CB_a_INIB_SINGLE_CELL_INIB
#define tSCt_no_CB_a_INIB_CB               tSCt_no_CB_a_INIB_INIB
#define tag_tSCt_no_CB_a_INIB_CB           tag_tSCt_no_CB_a_INIB_INIB

/* singleton cell CB prototype declaration #_SCP_# */
extern  tSCt_no_CB_a_INIB_INIB  tSCt_no_CB_a_INIB_SINGLE_CELL_INIB;


/* celltype IDX type #_CTIX_# */
typedef const struct tag_tSCt_no_CB_a_INIB_INIB *tSCt_no_CB_a_INIB_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* celll CB macro #_GCB_# */
#define tSCt_no_CB_a_INIB_GET_CELLCB(idx) ((void *)0)

/* attr access  #_AAM_# */
#define tSCt_no_CB_a_INIB_ATTR_size	(tSCt_no_CB_a_INIB_SINGLE_CELL_INIB.size)

#define tSCt_no_CB_a_INIB_GET_size()	(tSCt_no_CB_a_INIB_SINGLE_CELL_INIB.size)


/* var access macro #_VAM_# */
#define tSCt_no_CB_a_INIB_VAR_buf	(tSCt_no_CB_a_INIB_SINGLE_CELL_INIB.buf)

#define tSCt_no_CB_a_INIB_GET_buf()	(tSCt_no_CB_a_INIB_SINGLE_CELL_CB.buf)
#define tSCt_no_CB_a_INIB_SET_buf(val)	(tSCt_no_CB_a_INIB_SINGLE_CELL_CB.buf=(val))

#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tSCt_no_CB_a_INIB_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tSCt_no_CB_a_INIB_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tSCt_no_CB_a_INIB_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_size            tSCt_no_CB_a_INIB_ATTR_size


/* var access macro (abbrev) #_VAMA_# */
#define VAR_buf              tSCt_no_CB_a_INIB_VAR_buf



/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB()
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tSCt_no_CB_a_INIB_TECSGENH */
