/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tPutStringStdio_tecsgen.h"
#include "tPutStringStdio_factory.h"

/* entry port descriptor type #_EDT_# */
/* ePutString */
struct tag_tPutStringStdio_ePutString_DES {
    const struct tag_sPutString_VMT *vmt;
    int           idx;
};

/* entry port skelton function #_EPSF_# */
/* ePutString */
void           tPutStringStdio_ePutString_putString_skel( const struct tag_sPutString_VDES *epd, const char_t* string)
{
    struct tag_tPutStringStdio_ePutString_DES *lepd
        = (struct tag_tPutStringStdio_ePutString_DES *)epd;
    tPutStringStdio_ePutString_putString( lepd->idx, string );
}

/* entry port skelton function table #_EPSFT_# */
/* ePutString */
const struct tag_sPutString_VMT tPutStringStdio_ePutString_MT_ = {
    tPutStringStdio_ePutString_putString_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* entry port descriptor #_EPD_# */
extern const struct tag_tPutStringStdio_ePutString_DES PutStringStdio_ePutString_des;
const struct tag_tPutStringStdio_ePutString_DES PutStringStdio_ePutString_des = {
    &tPutStringStdio_ePutString_MT_,
    0,
};
