/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tAttributeSt_TECSGEN_H
#define tAttributeSt_TECSGEN_H

/*
 * celltype          :  tAttributeSt
 * global name       :  tAttributeSt
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sMain_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tAttributeSt_INIB {
    /* call port #_NEP_# */ 
    /* attribute(RO) #_ATO_# */ 
    int32_t        size;
    const struct tTag*   st_array;
}  tAttributeSt_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tAttributeSt_CB_tab           tAttributeSt_INIB_tab
#define tAttributeSt_CB               tAttributeSt_INIB
#define tag_tAttributeSt_CB           tag_tAttributeSt_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tAttributeSt_INIB  tAttributeSt_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tAttributeSt_INIB *tAttributeSt_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sMain */
ER           tAttributeSt_eMain_main(tAttributeSt_IDX idx);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tAttributeSt_ID_BASE        (1)  /* ID Base  #_NIDB_# */
#define tAttributeSt_N_CELL         (2)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tAttributeSt_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tAttributeSt_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tAttributeSt_ATTR_size( p_that )	((p_that)->size)
#define tAttributeSt_ATTR_st_array( p_that )	((p_that)->st_array)

#define tAttributeSt_GET_size(p_that)	((p_that)->size)
#define tAttributeSt_GET_st_array(p_that)	((p_that)->st_array)



#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
ER             tAttributeSt_eMain_main_skel( const struct tag_sMain_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tAttributeSt_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tAttributeSt_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tAttributeSt_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tAttributeSt_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_size            tAttributeSt_ATTR_size( p_cellcb )
#define ATTR_st_array        tAttributeSt_ATTR_st_array( p_cellcb )





/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tAttributeSt_eMain_main

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tAttributeSt_N_CELL; (i)++ ){ \
       (p_cb) = &tAttributeSt_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tAttributeSt_TECSGENH */
