/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tAttribute2_tecsgen.h"
#include "tAttribute2_factory.h"

/* entry port descriptor type #_EDT_# */
/* eMain : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eMain : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eMain : omitted by entry port optimize */

/* var (struct, array) initial value #_AVI_# */
const int32_t	tAttribute2_array_VAR_INIT[2] = { 1, 2, };

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
const const int32_t tAttribute2_Cell2_CB_sizeArray_INIT[2] = { 1, 2, };
int32_t tAttribute2_Cell2_CB_array_INIT[2];
/* cell INIB #_INIB_# */
tAttribute2_INIB tAttribute2_INIB_tab[] = {
    /* cell: tAttribute2_CB_tab[0]:  Cell2 id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        tAttribute2_Cell2_CB_sizeArray_INIT,     /* sizeArray */
        (int8_t*)0x1,                            /* p */
        2,                                       /* size */
        tAttribute2_Cell2_CB_array_INIT,         /* array */
    },
};

/* entry port descriptor #_EPD_# */
/* eMain : omitted by entry port optimize */
/* CB initialize code #_CIC_# */
void
tAttribute2_CB_initialize()
{
    tAttribute2_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
