/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tAttribute4_TECSGEN_H
#define tAttribute4_TECSGEN_H

/*
 * celltype          :  tAttribute4
 * global name       :  tAttribute4
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tAttribute4_INIB {
    /* attribute(RO) #_ATO_# */ 
    char*          buf0[2];
}  tAttribute4_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tAttribute4_CB_tab           tAttribute4_INIB_tab
#define tAttribute4_CB               tAttribute4_INIB
#define tag_tAttribute4_CB           tag_tAttribute4_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tAttribute4_INIB  tAttribute4_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tAttribute4_INIB *tAttribute4_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tAttribute4_ID_BASE         (1)  /* ID Base  #_NIDB_# */
#define tAttribute4_N_CELL          (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tAttribute4_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tAttribute4_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tAttribute4_ATTR_buf0( p_that )	((p_that)->buf0)

#define tAttribute4_GET_buf0(p_that)	((p_that)->buf0)



#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tAttribute4_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tAttribute4_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tAttribute4_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tAttribute4_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_buf0            tAttribute4_ATTR_buf0( p_cellcb )




/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tAttribute4_N_CELL; (i)++ ){ \
       (p_cb) = &tAttribute4_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tAttribute4_TECSGENH */
