/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCell_serv_tecsgen.h"
#include "tCell_serv_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntry : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eEntry : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eEntry : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tCell_serv_INIB tCell_serv_INIB_tab[] = {
    /* cell: tCell_serv_CB_tab[0]:  cell_serv id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        5,                                       /* a */
    },
    /* cell: tCell_serv_CB_tab[1]:  cell_serv2 id=2 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        5,                                       /* a */
    },
};

/* entry port descriptor #_EPD_# */
/* eEntry : omitted by entry port optimize */
/* eEntry : omitted by entry port optimize */
