/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tCell1_TECSGEN_H
#define tCell1_TECSGEN_H

/*
 * celltype          :  tCell1
 * global name       :  tCell1
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sSig1_tecsgen.h"
#include "sSig2_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tCell1_INIB {
    /* call port #_TCP_# */
    const struct tag_tCell_serv_INIB * const cCall;  /* TCP_4 */
    /* call port #_NEP_# */ 
    /* attribute(RO) #_ATO_# */ 
    int32_t        a;
}  tCell1_INIB;
/* cell CB type definition #_CCTPA_# */
typedef struct tag_tCell1_CB {
    tCell1_INIB  *_inib;
    /* call port #_TCP_# */
    /* call port #_NEP_# */ 
    /* var #_VA_# */ 
    int32_t        b;
}  tCell1_CB;
/* singleton cell CB prototype declaration #_MCPB_# */
extern tCell1_CB  tCell1_CB_tab[];

/* celltype IDX type #_CTIX_# */
typedef struct tag_tCell1_CB *tCell1_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sSig2 */
ER           tCell1_eEntry_func1(tCell1_IDX idx, int32_t a);
int32_t      tCell1_eEntry_func2(tCell1_IDX idx, int32_t a);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tCell1_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tCell_serv_tecsgen.h"
#ifdef  tCell1_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tCell1_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tCell1_ID_BASE              (1)  /* ID Base  #_NIDB_# */
#define tCell1_N_CELL               (3)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tCell1_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tCell1_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tCell1_ATTR_a( p_that )	((p_that)->_inib->a)

#define tCell1_GET_a(p_that)	((p_that)->_inib->a)


/* var access macro #_VAM_# */
#define tCell1_VAR_b(p_that)	((p_that)->b)

#define tCell1_GET_b(p_that)	((p_that)->b)
#define tCell1_SET_b(p_that,val)	((p_that)->b=(val))

#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tCell1_cCall_func1( p_that, a ) \
	  tCell_serv_eEntry_func1( \
	   (p_that)->_inib->cCall, (a) )
#define tCell1_cCall_func2( p_that, a ) \
	  tCell_serv_eEntry_func2( \
	   (p_that)->_inib->cCall, (a) )

#else  /* TECSFLOW */
#define tCell1_cCall_func1( p_that, a ) \
	  (p_that)->cCall.func1__T( \
 (a) )
#define tCell1_cCall_func2( p_that, a ) \
	  (p_that)->cCall.func2__T( \
 (a) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tCell1_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tCell1_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tCell1_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tCell1_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_a               tCell1_ATTR_a( p_cellcb )


/* var access macro (abbrev) #_VAMA_# */
#define VAR_b                tCell1_VAR_b( p_cellcb )

/* call port function macro (abbrev) #_CPMA_# */
#define cCall_func1( a ) \
          ((void)p_cellcb, tCell1_cCall_func1( p_cellcb, a ))
#define cCall_func2( a ) \
          ((void)p_cellcb, tCell1_cCall_func2( p_cellcb, a ))




/* entry port function macro (abbrev) #_EPM_# */
#define eEntry_func1     tCell1_eEntry_func1
#define eEntry_func2     tCell1_eEntry_func2

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tCell1_N_CELL; (i)++ ){ \
       (p_cb) = &tCell1_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)\
	(p_that)->b = tCell1_ATTR_a(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	(p_that)->_inib = &tCell1_INIB_tab[(i)];

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tCell1_TECSGENH */
