/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef sHello_TECSGEN_H
#define sHello_TECSGEN_H

/*
 * signature   :  sHello
 * global name :  sHello
 * context     :  task
 */

#ifndef TOPPERS_MACRO_ONLY

/* signature descriptor #_SD_# */
struct tag_sHello_VDES {
    struct tag_sHello_VMT *VMT;
};

/* signature function table #_SFT_# */
struct tag_sHello_VMT {
    void           (*hello__T)( const struct tag_sHello_VDES *edp );
};

/* signature descriptor #_SDES_# for dynamic join */
#ifndef Descriptor_of_sHello_Defined
#define  Descriptor_of_sHello_Defined
typedef struct { struct tag_sHello_VDES *vdes; } Descriptor( sHello );
#endif
#endif /* TOPPERS_MACRO_ONLY */

/* function id */
#define	FUNCID_SHELLO_HELLO                    (1)

#endif /* sHello_TECSGEN_H */
