/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tMainSingleArrayForComp_TECSGEN_H
#define tMainSingleArrayForComp_TECSGEN_H

/*
 * celltype          :  tMainSingleArrayForComp
 * global name       :  tMainSingleArrayForComp
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  yes
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sTaskBody_tecsgen.h"
#include "sHello_tecsgen.h"
#include "sTalkerSelector_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tMainSingleArrayForComp_CB {
    /* call port #_TCP_# */
    struct tag_sHello_VDES const*cDefaultTalker; /* TCP_2 */
    struct tag_sHello_VDES **cTalker; /* TCP_2 */
    int_t n_cTalker;  /* TCP_3 */
    struct tag_sHello_VDES **cTalker2; /* TCP_2 */
    /* call port #_NEP_# */ 
}  tMainSingleArrayForComp_CB;
/* singleton cell CB prototype declaration #_SCP_# */
extern  tMainSingleArrayForComp_CB  tMainSingleArrayForComp_SINGLE_CELL_CB;


/* celltype IDX type #_CTIX_# */
typedef struct tag_tMainSingleArrayForComp_CB *tMainSingleArrayForComp_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sTaskBody */
void         tMainSingleArrayForComp_eMain_main();
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tMainSingleArrayForComp_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tTalkerSelector_tecsgen.h"
#ifdef  tMainSingleArrayForComp_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tMainSingleArrayForComp_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

/* call port array size macro #_NCPA_# */
#define N_CP_cTalker  (tMainSingleArrayForComp_SINGLE_CELL_CB.n_cTalker)
#define NCP_cTalker   (tMainSingleArrayForComp_SINGLE_CELL_CB.n_cTalker)
#define N_CP_cTalker2    (2)
#define NCP_cTalker2     (2)
/* optional call port test macro #_TOCP_# */
#define tMainSingleArrayForComp_is_cTalker2_joined(subscript) \
	  ((tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker2!=0) \
	  &&(tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker2[subscript]!=0))

/* celll CB macro #_GCB_# */
#define tMainSingleArrayForComp_GET_CELLCB(idx) ((void *)0)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tMainSingleArrayForComp_cDefaultTalker_hello( ) \
	  tMainSingleArrayForComp_SINGLE_CELL_CB.cDefaultTalker->VMT->hello__T( \
	  tMainSingleArrayForComp_SINGLE_CELL_CB.cDefaultTalker )
#define tMainSingleArrayForComp_cTalker_hello( subscript ) \
	  tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker[subscript]->VMT->hello__T( \
	  tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker[subscript] )
#define tMainSingleArrayForComp_cTalker2_hello( subscript ) \
	  tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker2[subscript]->VMT->hello__T( \
	  tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker2[subscript] )
#define tMainSingleArrayForComp_cTalkerSelector_getTalker( talker, i ) \
	  tTalkerSelector_eTalkerSelector_getTalker( \
	   &tTalkerSelector_CB_tab[1], (talker), (i) )
#define tMainSingleArrayForComp_cTalkerSelector_getNTalker( n ) \
	  tTalkerSelector_eTalkerSelector_getNTalker( \
	   &tTalkerSelector_CB_tab[1], (n) )

#else  /* TECSFLOW */
#define tMainSingleArrayForComp_cDefaultTalker_hello( ) \
	  (p_that)->cDefaultTalker.hello__T( \
 )
#define tMainSingleArrayForComp_cTalker_hello( subscript ) \
	  (p_that)->cTalker[subscript].hello__T( \
 )
#define tMainSingleArrayForComp_cTalker2_hello( subscript ) \
	  (p_that)->cTalker2[subscript].hello__T( \
 )
#define tMainSingleArrayForComp_cTalkerSelector_getTalker( talker, i ) \
	  (p_that)->cTalkerSelector.getTalker__T( \
 (talker), (i) )
#define tMainSingleArrayForComp_cTalkerSelector_getNTalker( n ) \
	  (p_that)->cTalkerSelector.getNTalker__T( \
 (n) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
void           tMainSingleArrayForComp_eMain_main_skel( const struct tag_sTaskBody_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

/* refer to descriptor function #_CRD_# */
/* [ref_desc] cDefaultTalker */
Inline Descriptor( sHello )
tMainSingleArrayForComp_cDefaultTalker_refer_to_descriptor(  )
{
    Descriptor( sHello )  des;
    /* cast is ncecessary for removing 'const'  */
    des.vdes = (struct tag_sHello_VDES *)tMainSingleArrayForComp_SINGLE_CELL_CB.cDefaultTalker;
    return des;
}

/* set descriptor function #_SDF_# */
/* [dynamic] cTalker */
Inline void
tMainSingleArrayForComp_cTalker_set_descriptor( int_t  i, Descriptor( sHello ) des )
{
    assert( des.vdes != NULL );
    assert( 0 <= i && i < NCP_cTalker );
    tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker[ i ] = des.vdes;
}

/* [dynamic] cTalker2 */
Inline void
tMainSingleArrayForComp_cTalker2_set_descriptor( int_t  i, Descriptor( sHello ) des )
{
    assert( des.vdes != NULL );
    assert( 0 <= i && i < NCP_cTalker2 );
    tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker2[ i ] = des.vdes;
}

/* [dynamic,optional] cTalker2 */
Inline void
tMainSingleArrayForComp_cTalker2_unjoin(  int_t  i  )
{
    tMainSingleArrayForComp_SINGLE_CELL_CB.cTalker2[ i ] = NULL;
}

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tMainSingleArrayForComp_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tMainSingleArrayForComp_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tMainSingleArrayForComp_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cDefaultTalker_hello( ) \
          tMainSingleArrayForComp_cDefaultTalker_hello( )
#define cTalker_hello( subscript ) \
          tMainSingleArrayForComp_cTalker_hello( subscript )
#define cTalker2_hello( subscript ) \
          tMainSingleArrayForComp_cTalker2_hello( subscript )
#define cTalkerSelector_getTalker( talker, i ) \
          tMainSingleArrayForComp_cTalkerSelector_getTalker( talker, i )
#define cTalkerSelector_getNTalker( n ) \
          tMainSingleArrayForComp_cTalkerSelector_getNTalker( n )


/* refer to descriptor macro (abbrev) #_CRDA_# */
#define cDefaultTalker_refer_to_descriptor()\
          tMainSingleArrayForComp_cDefaultTalker_refer_to_descriptor(  )
#define cDefaultTalker_ref_desc()\
          cDefaultTalker_refer_to_descriptor()


/* set descriptor macro (abbrev) #_SDMA_# */
#define cTalker_set_descriptor( i, desc )\
          tMainSingleArrayForComp_cTalker_set_descriptor( i, desc )
#define cTalker_unjoin( i )\
          tMainSingleArrayForComp_cTalker_unjoin( i )
#define cTalker2_set_descriptor( i, desc )\
          tMainSingleArrayForComp_cTalker2_set_descriptor( i, desc )
#define cTalker2_unjoin( i )\
          tMainSingleArrayForComp_cTalker2_unjoin( i )

/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cTalker2_joined(subscript)\
		tMainSingleArrayForComp_is_cTalker2_joined(subscript)

/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tMainSingleArrayForComp_eMain_main

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB()
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tMainSingleArrayForComp_TECSGENH */
