/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tMainArray_TECSGEN_H
#define tMainArray_TECSGEN_H

/*
 * celltype          :  tMainArray
 * global name       :  tMainArray
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sTaskBody_tecsgen.h"
#include "sHello_tecsgen.h"
#include "sTalkerSelector_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tMainArray_INIB {
    /* call port #_TCP_# */
    struct tag_sHello_VDES const*cDefaultTalker; /* TCP_2 */
    struct tag_sHello_VDES *const*cTalker_init_; /* TCP_1 */
    struct tag_sHello_VDES **cTalker; /* TCP_2 */
    int_t n_cTalker;  /* TCP_3 */
    struct tag_sHello_VDES *const*cTalker2_init_; /* TCP_1 */
    struct tag_sHello_VDES **cTalker2; /* TCP_2 */
    const struct tag_tTalkerSelector_INIB * const cTalkerSelector;  /* TCP_4 */
    /* call port #_NEP_# */ 
}  tMainArray_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tMainArray_CB_tab           tMainArray_INIB_tab
#define tMainArray_CB               tMainArray_INIB
#define tag_tMainArray_CB           tag_tMainArray_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tMainArray_INIB  tMainArray_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tMainArray_INIB *tMainArray_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sTaskBody */
void         tMainArray_eMain_main(tMainArray_IDX idx);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tMainArray_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tTalkerSelector_tecsgen.h"
#ifdef  tMainArray_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tMainArray_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tMainArray_ID_BASE          (1)  /* ID Base  #_NIDB_# */
#define tMainArray_N_CELL           (2)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tMainArray_VALID_IDX(IDX) (1)

/* call port array size macro #_NCPA_# */
#define N_CP_cTalker(p_that)  ((p_that)->n_cTalker)
#define NCP_cTalker           (N_CP_cTalker(p_cellcb))
#define N_CP_cTalker2    (2)
#define NCP_cTalker2     (2)
/* optional call port test macro #_TOCP_# */
#define tMainArray_is_cTalker2_joined(p_that,subscript) \
	  (((p_that)->cTalker2!=0)\
	  &&((p_that)->cTalker2[subscript]!=0))

/* celll CB macro #_GCB_# */
#define tMainArray_GET_CELLCB(idx) (idx)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tMainArray_cDefaultTalker_hello( p_that ) \
	  (p_that)->cDefaultTalker->VMT->hello__T( \
	   (p_that)->cDefaultTalker )
#define tMainArray_cTalker_hello( p_that, subscript ) \
	  (p_that)->cTalker[subscript]->VMT->hello__T( \
	   (p_that)->cTalker[subscript] )
#define tMainArray_cTalker2_hello( p_that, subscript ) \
	  (p_that)->cTalker2[subscript]->VMT->hello__T( \
	   (p_that)->cTalker2[subscript] )
#define tMainArray_cTalkerSelector_getTalker( p_that, talker, i ) \
	  tTalkerSelector_eTalkerSelector_getTalker( \
	   (p_that)->cTalkerSelector, (talker), (i) )
#define tMainArray_cTalkerSelector_getNTalker( p_that, n ) \
	  tTalkerSelector_eTalkerSelector_getNTalker( \
	   (p_that)->cTalkerSelector, (n) )

#else  /* TECSFLOW */
#define tMainArray_cDefaultTalker_hello( p_that ) \
	  (p_that)->cDefaultTalker.hello__T( \
 )
#define tMainArray_cTalker_hello( p_that, subscript ) \
	  (p_that)->cTalker[subscript].hello__T( \
 )
#define tMainArray_cTalker2_hello( p_that, subscript ) \
	  (p_that)->cTalker2[subscript].hello__T( \
 )
#define tMainArray_cTalkerSelector_getTalker( p_that, talker, i ) \
	  (p_that)->cTalkerSelector.getTalker__T( \
 (talker), (i) )
#define tMainArray_cTalkerSelector_getNTalker( p_that, n ) \
	  (p_that)->cTalkerSelector.getNTalker__T( \
 (n) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
void           tMainArray_eMain_main_skel( const struct tag_sTaskBody_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

/* refer to descriptor function #_CRD_# */
/* [ref_desc] cDefaultTalker */
Inline Descriptor( sHello )
tMainArray_cDefaultTalker_refer_to_descriptor( tMainArray_CB  *p_that )
{
    Descriptor( sHello )  des;
    tMainArray_CB *p_cellcb = p_that;
    /* cast is ncecessary for removing 'const'  */
    des.vdes = (struct tag_sHello_VDES *)p_cellcb->cDefaultTalker;
    return des;
}

/* set descriptor function #_SDF_# */
/* [dynamic] cTalker */
Inline void
tMainArray_cTalker_set_descriptor( tMainArray_CB  *p_that, int_t  i, Descriptor( sHello ) des )
{
    tMainArray_CB *p_cellcb = p_that;
    assert( des.vdes != NULL );
    assert( 0 <= i && i < NCP_cTalker );
    (p_cellcb)->cTalker[ i ] = des.vdes;
}

/* [dynamic] cTalker2 */
Inline void
tMainArray_cTalker2_set_descriptor( tMainArray_CB  *p_that, int_t  i, Descriptor( sHello ) des )
{
    tMainArray_CB *p_cellcb = p_that;
    assert( des.vdes != NULL );
    assert( 0 <= i && i < NCP_cTalker2 );
    (p_cellcb)->cTalker2[ i ] = des.vdes;
}

/* [dynamic,optional] cTalker2 */
Inline void
tMainArray_cTalker2_unjoin( tMainArray_CB  *p_that ,  int_t  i  )
{
    tMainArray_CB *p_cellcb = p_that;
    (p_cellcb)->cTalker2[ i ] = NULL;
}

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tMainArray_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tMainArray_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tMainArray_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tMainArray_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cDefaultTalker_hello( ) \
          tMainArray_cDefaultTalker_hello( p_cellcb )
#define cTalker_hello( subscript ) \
          tMainArray_cTalker_hello( p_cellcb, subscript )
#define cTalker2_hello( subscript ) \
          tMainArray_cTalker2_hello( p_cellcb, subscript )
#define cTalkerSelector_getTalker( talker, i ) \
          ((void)p_cellcb, tMainArray_cTalkerSelector_getTalker( p_cellcb, talker, i ))
#define cTalkerSelector_getNTalker( n ) \
          ((void)p_cellcb, tMainArray_cTalkerSelector_getNTalker( p_cellcb, n ))


/* refer to descriptor macro (abbrev) #_CRDA_# */
#define cDefaultTalker_refer_to_descriptor()\
          tMainArray_cDefaultTalker_refer_to_descriptor( p_cellcb )
#define cDefaultTalker_ref_desc()\
          cDefaultTalker_refer_to_descriptor()


/* set descriptor macro (abbrev) #_SDMA_# */
#define cTalker_set_descriptor( i, desc )\
          tMainArray_cTalker_set_descriptor( p_cellcb, i, desc )
#define cTalker_unjoin( i )\
          tMainArray_cTalker_unjoin( p_cellcb, i )
#define cTalker2_set_descriptor( i, desc )\
          tMainArray_cTalker2_set_descriptor( p_cellcb, i, desc )
#define cTalker2_unjoin( i )\
          tMainArray_cTalker2_unjoin( p_cellcb, i )

/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cTalker2_joined(subscript)\
		tMainArray_is_cTalker2_joined(p_cellcb,subscript)

/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tMainArray_eMain_main

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tMainArray_N_CELL; (i)++ ){ \
       (p_cb) = &tMainArray_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)\
     {                                                                          \
        int_t   j;                                                              \
        for( j = 0; j < N_CP_cTalker(p_that); j++ ){                            \
            (p_that)->cTalker[j] = (p_that)->cTalker_init_[j];                  \
        }                                                                       \
       }                                                                        \
     {                                                                          \
        int_t   j;                                                              \
        for( j = 0; j < N_CP_cTalker2; j++ ){                                   \
            (p_that)->cTalker2[j] = (p_that)->cTalker2_init_[j];                \
        }                                                                       \
       }                                                                        

#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tMainArray_TECSGENH */
