/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tCell1_TECSGEN_H
#define tCell1_TECSGEN_H

/*
 * celltype          :  tCell1
 * global name       :  tCell1
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  no
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sSig1_tecsgen.h"
#include "sSig2_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tCell1_INIB {
    /* call port #_TCP_# */
    const struct tag_tCell2_INIB * const cCall1;  /* TCP_4 */
    /* call port #_NEP_# */ 
    /* attribute(RO) #_ATO_# */ 
    char*          name;
    int32_t        a;
}  tCell1_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tCell1_CB_tab           tCell1_INIB_tab
#define tCell1_CB               tCell1_INIB
#define tag_tCell1_CB           tag_tCell1_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tCell1_INIB  tCell1_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tCell1_INIB *tCell1_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sSig1 */
int32_t      tCell1_eEntry1_func1(tCell1_IDX idx, int32_t a);
int32_t      tCell1_eEntry1_func2(tCell1_IDX idx, int32_t a);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tCell1_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#include "tCell2_tecsgen.h"
#ifdef  tCell1_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tCell1_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tCell1_ID_BASE              (1)  /* ID Base  #_NIDB_# */
#define tCell1_N_CELL               (4)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tCell1_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tCell1_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tCell1_ATTR_name( p_that )	((p_that)->name)
#define tCell1_ATTR_a( p_that )	((p_that)->a)

#define tCell1_GET_name(p_that)	((p_that)->name)
#define tCell1_GET_a(p_that)	((p_that)->a)



#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tCell1_cCall1_func1( p_that, a ) \
	  tCell2_eEntry2_func1( \
	   (p_that)->cCall1, (a) )
#define tCell1_cCall1_func2( p_that, a ) \
	  tCell2_eEntry2_func2( \
	   (p_that)->cCall1, (a) )

#else  /* TECSFLOW */
#define tCell1_cCall1_func1( p_that, a ) \
	  (p_that)->cCall1.func1__T( \
 (a) )
#define tCell1_cCall1_func2( p_that, a ) \
	  (p_that)->cCall1.func2__T( \
 (a) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eEntry1 */
int32_t        tCell1_eEntry1_func1_skel( const struct tag_sSig1_VDES *epd, int32_t a);
int32_t        tCell1_eEntry1_func2_skel( const struct tag_sSig1_VDES *epd, int32_t a);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tCell1_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tCell1_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tCell1_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tCell1_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_name            tCell1_ATTR_name( p_cellcb )
#define ATTR_a               tCell1_ATTR_a( p_cellcb )


/* call port function macro (abbrev) #_CPMA_# */
#define cCall1_func1( a ) \
          ((void)p_cellcb, tCell1_cCall1_func1( p_cellcb, a ))
#define cCall1_func2( a ) \
          ((void)p_cellcb, tCell1_cCall1_func2( p_cellcb, a ))




/* entry port function macro (abbrev) #_EPM_# */
#define eEntry1_func1    tCell1_eEntry1_func1
#define eEntry1_func2    tCell1_eEntry1_func2

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tCell1_N_CELL; (i)++ ){ \
       //(p_cb) = &tCell1_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tCell1_TECSGENH */
