/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCt_tecsgen.h"
#include "tCt_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEnt */
struct tag_tCt_eEnt_DES {
    const struct tag_sSig_VMT *vmt;
    tCt_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eEnt */
int32_t        tCt_eEnt_func_skel( const struct tag_sSig_VDES *epd, int32_t in, int32_t* out)
{
    struct tag_tCt_eEnt_DES *lepd
        = (struct tag_tCt_eEnt_DES *)epd;
    return tCt_eEnt_func( lepd->idx, in, out );
}

/* entry port skelton function table #_EPSFT_# */
/* eEnt */
const struct tag_sSig_VMT tCt_eEnt_MT_ = {
    tCt_eEnt_func_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
/* cell: C0_CB:  C0 id=1 */
const tCt_INIB C0_INIB = {
    /* entry port #_EP_# */ 
    /* attribute(RO) */ 
    20,                                      /* a */
};

/* cell: C1_CB:  C1 id=2 */
const tCt_INIB C1_INIB = {
    /* entry port #_EP_# */ 
    /* attribute(RO) */ 
    20,                                      /* a */
};

/* cell CB #_CB_# */
/* cell: C0_CB:  C0 id=1 */
tCt_CB C0_CB = {};
/* cell: C1_CB:  C1 id=2 */
tCt_CB C1_CB = {};
/* entry port descriptor #_EPD_# */
extern const struct tag_tCt_eEnt_DES C0_eEnt_des;
const struct tag_tCt_eEnt_DES C0_eEnt_des = {
    &tCt_eEnt_MT_,
    1,     /* ID */
};
extern const struct tag_tCt_eEnt_DES C1_eEnt_des;
const struct tag_tCt_eEnt_DES C1_eEnt_des = {
    &tCt_eEnt_MT_,
    2,     /* ID */
};
/* ID to INIB table #_INTAB_# */
tCt_INIB *const tCt_INIB_ptab[] ={
    &C0_INIB,
    &C1_INIB,
};
/* ID to CB table #_CBTAB_# */
tCt_CB *const tCt_CB_ptab[] ={
    &C0_CB,
    &C1_CB,
};
/* CB initialize code #_CIC_# */
void
tCt_CB_initialize()
{
    tCt_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
