/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tSingle_idx_is_id_tecsgen.h"
#include "tSingle_idx_is_id_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* entry port descriptor #_EPD_# */
/* CB initialize code #_CIC_# */
void
tSingle_idx_is_id_CB_initialize()
{
    SET_CB_INIB_POINTER(i,p_cb)
    INITIALIZE_CB()
}
