/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tNCPArray_templ.c => src/tNCPArray.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cCall signature: sSig context:task optional:true
 *   bool_t     is_cCall_joined(int subscript)        check if joined
 *   void           cCall_func( subscript );
 *   int32_t        cCall_func2( subscript, int32_t arg );
 *   struct tagST   cCall_func3( subscript, struct tagST a );
 *       subscript:  0...(NCP_cCall-1)
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tNCPArray_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
