/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tNCPArray_TECSGEN_H
#define tNCPArray_TECSGEN_H

/*
 * celltype          :  tNCPArray
 * global name       :  tNCPArray
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sSig_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tNCPArray_CB {
    /* call port #_TCP_# */
    struct tag_sSig_VDES *const*cCall; /* TCP_2 */
    int_t n_cCall;  /* TCP_3 */
}  tNCPArray_CB;
/* singleton cell CB prototype declaration #_MCPB_# */
extern tNCPArray_CB  tNCPArray_CB_tab[];

/* celltype IDX type #_CTIX_# */
typedef struct tag_tNCPArray_CB *tNCPArray_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tNCPArray_ID_BASE           (1)  /* ID Base  #_NIDB_# */
#define tNCPArray_N_CELL            (2)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tNCPArray_VALID_IDX(IDX) (1)

/* call port array size macro #_NCPA_# */
#define N_CP_cCall(p_that)  ((p_that)->n_cCall)
#define NCP_cCall           (N_CP_cCall(p_cellcb))
/* optional call port test macro #_TOCP_# */
#define tNCPArray_is_cCall_joined(p_that,subscript) \
	  (((p_that)->cCall!=0)\
	  &&((p_that)->cCall[subscript]!=0))

/* celll CB macro #_GCB_# */
#define tNCPArray_GET_CELLCB(idx) (idx)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tNCPArray_cCall_func( p_that, subscript ) \
	  (p_that)->cCall[subscript]->VMT->func__T( \
	   (p_that)->cCall[subscript] )
#define tNCPArray_cCall_func2( p_that, subscript, arg ) \
	  (p_that)->cCall[subscript]->VMT->func2__T( \
	   (p_that)->cCall[subscript], (arg) )
#define tNCPArray_cCall_func3( p_that, subscript, a ) \
	  (p_that)->cCall[subscript]->VMT->func3__T( \
	   (p_that)->cCall[subscript], (a) )

#else  /* TECSFLOW */
#define tNCPArray_cCall_func( p_that, subscript ) \
	  (p_that)->cCall[subscript].func__T( \
 )
#define tNCPArray_cCall_func2( p_that, subscript, arg ) \
	  (p_that)->cCall[subscript].func2__T( \
 (arg) )
#define tNCPArray_cCall_func3( p_that, subscript, a ) \
	  (p_that)->cCall[subscript].func3__T( \
 (a) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tNCPArray_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tNCPArray_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tNCPArray_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tNCPArray_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cCall_func( subscript ) \
          tNCPArray_cCall_func( p_cellcb, subscript )
#define cCall_func2( subscript, arg ) \
          tNCPArray_cCall_func2( p_cellcb, subscript, arg )
#define cCall_func3( subscript, a ) \
          tNCPArray_cCall_func3( p_cellcb, subscript, a )



/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cCall_joined(subscript)\
		tNCPArray_is_cCall_joined(p_cellcb,subscript)
/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tNCPArray_N_CELL; (i)++ ){ \
       (p_cb) = &tNCPArray_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tNCPArray_TECSGENH */
