/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tSendRecvClnt_TECSGEN_H
#define tSendRecvClnt_TECSGEN_H

/*
 * celltype          :  tSendRecvClnt
 * global name       :  tSendRecvClnt
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  no
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sTaskBody_tecsgen.h"
#include "sSigSendRecv_tecsgen.h"
#include "sAlloc_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tSendRecvClnt_CB {
    /* call port #_TCP_# */
    /* call port #_NEP_# */ 
}  tSendRecvClnt_CB;
/* singleton cell CB prototype declaration #_MCPB_# */

/* celltype IDX type #_CTIX_# */
typedef int   tSendRecvClnt_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sTaskBody */
void         tSendRecvClnt_eMain_main(tSendRecvClnt_IDX idx);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

/* to get the definition of CB type of referenced celltype for optimization #_ICT_# */
#ifndef  TOPPERS_CB_TYPE_ONLY
#define  tSendRecvClnt_CB_TYPE_ONLY
#define TOPPERS_CB_TYPE_ONLY
#endif  /* TOPPERS_CB_TYPE_ONLY */
#ifdef  tSendRecvClnt_CB_TYPE_ONLY
#undef TOPPERS_CB_TYPE_ONLY
#endif /* tSendRecvClnt_CB_TYPE_ONLY */
#ifndef TOPPERS_CB_TYPE_ONLY

#define tSendRecvClnt_ID_BASE        (1)  /* ID Base  #_NIDB_# */
#define tSendRecvClnt_N_CELL        (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tSendRecvClnt_VALID_IDX(IDX) (1)

/* optional call port test macro #_TOCP_# */
#define tSendRecvClnt_is_cCall_joined(p_that) \
	  (0)    /* not joined */
#define tSendRecvClnt_is_cCall_snd_st_val_joined(p_that) \
	  (0)    /* not joined */
#define tSendRecvClnt_is_cCall_rcv_st_val_joined(p_that) \
	  (0)    /* not joined */

/* celll CB macro #_GCB_# */
#define tSendRecvClnt_GET_CELLCB(idx) ((void *)0)
#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tSendRecvClnt_cCall_snd( p_that, st_val ) \
	  ((ER (*)())0)()
	  /* optional no entry port joined */
#define tSendRecvClnt_cCall_rcv( p_that, st_val ) \
	  ((ER (*)())0)()
	  /* optional no entry port joined */
#define tSendRecvClnt_cCall_snd_st_val_alloc( p_that, size, p ) \
	  ((ER (*)())0)()
	  /* optional no entry port joined */
#define tSendRecvClnt_cCall_snd_st_val_dealloc( p_that, p ) \
	  ((ER (*)())0)()
	  /* optional no entry port joined */
#define tSendRecvClnt_cCall_rcv_st_val_alloc( p_that, size, p ) \
	  ((ER (*)())0)()
	  /* optional no entry port joined */
#define tSendRecvClnt_cCall_rcv_st_val_dealloc( p_that, p ) \
	  ((ER (*)())0)()
	  /* optional no entry port joined */

#else  /* TECSFLOW */
#define tSendRecvClnt_cCall_snd( p_that, st_val ) \
	  (p_that)->cCall.snd__T( \
 (st_val) )
#define tSendRecvClnt_cCall_rcv( p_that, st_val ) \
	  (p_that)->cCall.rcv__T( \
 (st_val) )
#define tSendRecvClnt_cCall_snd_st_val_alloc( p_that, size, p ) \
	  (p_that)->cCall_snd_st_val.alloc__T( \
 (size), (p) )
#define tSendRecvClnt_cCall_snd_st_val_dealloc( p_that, p ) \
	  (p_that)->cCall_snd_st_val.dealloc__T( \
 (p) )
#define tSendRecvClnt_cCall_rcv_st_val_alloc( p_that, size, p ) \
	  (p_that)->cCall_rcv_st_val.alloc__T( \
 (size), (p) )
#define tSendRecvClnt_cCall_rcv_st_val_dealloc( p_that, p ) \
	  (p_that)->cCall_rcv_st_val.dealloc__T( \
 (p) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eMain */
void           tSendRecvClnt_eMain_main_skel( const struct tag_sTaskBody_VDES *epd);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tSendRecvClnt_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tSendRecvClnt_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tSendRecvClnt_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tSendRecvClnt_IDX

/* call port function macro (abbrev) #_CPMA_# */
#define cCall_snd( st_val ) \
          ((void)p_cellcb, tSendRecvClnt_cCall_snd( p_cellcb, st_val ))
#define cCall_rcv( st_val ) \
          ((void)p_cellcb, tSendRecvClnt_cCall_rcv( p_cellcb, st_val ))
#define cCall_snd_st_val_alloc( size, p ) \
          ((void)p_cellcb, tSendRecvClnt_cCall_snd_st_val_alloc( p_cellcb, size, p ))
#define cCall_snd_st_val_dealloc( p ) \
          ((void)p_cellcb, tSendRecvClnt_cCall_snd_st_val_dealloc( p_cellcb, p ))
#define cCall_rcv_st_val_alloc( size, p ) \
          ((void)p_cellcb, tSendRecvClnt_cCall_rcv_st_val_alloc( p_cellcb, size, p ))
#define cCall_rcv_st_val_dealloc( p ) \
          ((void)p_cellcb, tSendRecvClnt_cCall_rcv_st_val_dealloc( p_cellcb, p ))



/* optional call port test macro (abbrev) #_TOCPA_# */
#define is_cCall_joined()\
		tSendRecvClnt_is_cCall_joined(p_cellcb)
#define is_cCall_snd_st_val_joined()\
		tSendRecvClnt_is_cCall_snd_st_val_joined(p_cellcb)
#define is_cCall_rcv_st_val_joined()\
		tSendRecvClnt_is_cCall_rcv_st_val_joined(p_cellcb)

/* entry port function macro (abbrev) #_EPM_# */
#define eMain_main       tSendRecvClnt_eMain_main

/* iteration code (FOREACH_CELL) (niether CB, nor NIB exit) #_NFEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for((i)=0;(i)<0;(i)++){

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */

/* deallocate macro #_DAL_#   */
#define CCALL_SND_ST_VAL_DEALLOC(st_val) \
	  cCall_snd_st_val_dealloc( (st_val) ); 
#define CCALL_RCV_ST_VAL_DEALLOC(st_val) \
	  cCall_rcv_st_val_dealloc( (st_val) ); 

/* deallocate macro #_DAL_#  _RESET */
#define CCALL_SND_ST_VAL_DEALLOC_RESET(st_val) \
	  if( (st_val) ){ \
	    cCall_snd_st_val_dealloc( (st_val) );  \
	  }
#define CCALL_RCV_ST_VAL_DEALLOC_RESET(st_val) \
	  if( (st_val) ){ \
	    cCall_rcv_st_val_dealloc( (st_val) );  \
	  }
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tSendRecvClnt_TECSGENH */
