/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef sSendRecv_TECSGEN_H
#define sSendRecv_TECSGEN_H

/*
 * signature   :  sSendRecv
 * global name :  sSendRecv
 * context     :  task
 */

#ifndef TOPPERS_MACRO_ONLY

/* signature descriptor #_SD_# */
struct tag_sSendRecv_VDES {
    struct tag_sSendRecv_VMT *VMT;
};

/* signature function table #_SFT_# */
struct tag_sSendRecv_VMT {
    void   (*dummy__)(void);
};

/* signature descriptor #_SDES_# for dynamic join */
#ifndef Descriptor_of_sSendRecv_Defined
#define  Descriptor_of_sSendRecv_Defined
typedef struct { struct tag_sSendRecv_VDES *vdes; } Descriptor( sSendRecv );
#endif
#endif /* TOPPERS_MACRO_ONLY */

/* function id */

#endif /* sSendRecv_TECSGEN_H */
