/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tTask_tecsgen.h"
#include "tTask_factory.h"

/* entry port descriptor type #_EDT_# */
/* eTask : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eTask : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eTask : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_sTaskBody_VDES Cl_eBody_des;

extern struct tag_sTaskBody_VDES Cl2_Cell_eBody_des;

/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tTask_INIB tTask_INIB_tab[] = {
    /* cell: tTask_CB_tab[0]:  Task1 id=1 */
    {
        /* call port (INIB) #_CP_# */ 
        0,                                       /* cTaskBody #_CCP2B_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        TA_ACT,                                  /* attribute */
        15,                                      /* priority */
        4096,                                    /* stackSize */
        "tTask_Task1",                           /* name */
    },
    /* cell: tTask_CB_tab[1]:  Task2 id=2 */
    {
        /* call port (INIB) #_CP_# */ 
        0,                                       /* cTaskBody #_CCP2B_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        TA_ACT,                                  /* attribute */
        15,                                      /* priority */
        4096,                                    /* stackSize */
        "tTask_Task2",                           /* name */
    },
};

/* cell CB #_CB_# */
struct tag_tTask_CB tTask_CB_tab[2];
/* entry port descriptor #_EPD_# */
/* eTask : omitted by entry port optimize */
/* eTask : omitted by entry port optimize */
/* CB initialize code #_CIC_# */
void
tTask_CB_initialize()
{
    tTask_CB	*p_cb;
    int		i;
    FOREACH_CELL(i,p_cb)
        SET_CB_INIB_POINTER(i,p_cb)
        INITIALIZE_CB(p_cb)
    END_FOREACH_CELL
}
