/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCell3_tecsgen.h"
#include "tCell3_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntry3 : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eEntry3 : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eEntry3 : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_sSig4_VDES comp1_comp12_cell4_eEntry4_des;

extern struct tag_sSig4_VDES comp2_comp12_cell4_eEntry4_des;

/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tCell3_INIB tCell3_INIB_tab[] = {
    /* cell: tCell3_CB_tab[0]:  comp1_comp12_cell3 id=1 */
    {
        /* call port (INIB) #_CP_# */ 
        &tCell4_INIB_tab[0],                     /* cCall3 #_CCP2_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        30,                                      /* a */
    },
    /* cell: tCell3_CB_tab[1]:  comp2_comp12_cell3 id=2 */
    {
        /* call port (INIB) #_CP_# */ 
        &tCell4_INIB_tab[1],                     /* cCall3 #_CCP2_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        30,                                      /* a */
    },
};

/* entry port descriptor #_EPD_# */
/* eEntry3 : omitted by entry port optimize */
/* eEntry3 : omitted by entry port optimize */
