/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCell4_tecsgen.h"
#include "tCell4_factory.h"

/* entry port descriptor type #_EDT_# */
/* eEntry4 : omitted by entry port optimize */

/* entry port skelton function #_EPSF_# */
/* eEntry4 : omitted by entry port optimize */

/* entry port skelton function table #_EPSFT_# */
/* eEntry4 : omitted by entry port optimize */

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */


/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tCell4_INIB tCell4_INIB_tab[] = {
    /* cell: tCell4_CB_tab[0]:  comp1_comp12_cell4 id=1 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        101,                                     /* a */
    },
    /* cell: tCell4_CB_tab[1]:  comp2_comp12_cell4 id=2 */
    {
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        10,                                      /* a */
    },
};

/* entry port descriptor #_EPD_# */
/* eEntry4 : omitted by entry port optimize */
/* eEntry4 : omitted by entry port optimize */
