/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tTestComponent2_TECSGEN_H
#define tTestComponent2_TECSGEN_H

/*
 * celltype          :  tTestComponent2
 * global name       :  tTestComponent2
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tTestComponent2_INIB {
    /* call port #_NEP_# */ 
    int_t n_eA;
}  tTestComponent2_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tTestComponent2_CB_tab           tTestComponent2_INIB_tab
#define tTestComponent2_CB               tTestComponent2_INIB
#define tag_tTestComponent2_CB           tag_tTestComponent2_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tTestComponent2_INIB  tTestComponent2_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tTestComponent2_INIB *tTestComponent2_IDX;

/* prototype declaration of entry port function #_EPP_# */
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tTestComponent2_ID_BASE        (1)  /* ID Base  #_NIDB_# */
#define tTestComponent2_N_CELL        (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tTestComponent2_VALID_IDX(IDX) (1)

/* entry port array size macro #_NEPA_# */
#define NEP_eA           ((p_cellcb)->n_eA)

/* celll CB macro #_GCB_# */
#define tTestComponent2_GET_CELLCB(idx) (idx)
#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tTestComponent2_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tTestComponent2_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tTestComponent2_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tTestComponent2_IDX




/* entry port function macro (abbrev) #_EPM_# */

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tTestComponent2_N_CELL; (i)++ ){ \
       (p_cb) = &tTestComponent2_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tTestComponent2_TECSGENH */
