/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCt_a_CB_a_INIB_tecsgen.h"
#include "tCt_a_CB_a_INIB_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
int8_t Ct_a_CB_a_INIB_CB_buf_INIT[6];
/* cell CB #_CB_# */
/* cell: Ct_a_CB_a_INIB_CB:  Ct_a_CB_a_INIB id=19 */
tCt_a_CB_a_INIB_CB Ct_a_CB_a_INIB_CB = {
    /* attribute */ 
    6,                                       /* size */
    Ct_a_CB_a_INIB_CB_buf_INIT,              /* buf */
    /* var */ 
    9,                                       /* a */
};

/* entry port descriptor #_EPD_# */
/* ID to CB table #_CBTAB_# */
tCt_a_CB_a_INIB_CB *const tCt_a_CB_a_INIB_CB_ptab[] ={
    &Ct_a_CB_a_INIB_CB,
};
