/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tCt_no_CB_no_INIB_TECSGEN_H
#define tCt_no_CB_no_INIB_TECSGEN_H

/*
 * celltype          :  tCt_no_CB_no_INIB
 * global name       :  tCt_no_CB_no_INIB
 * multi-domain      :  yes
 * idx_is_id(actual) :  yes(yes)
 * singleton         :  no
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tCt_no_CB_no_INIB_CB {
    int8_t*        buf;
    /* var #_VA_# */ 
}  tCt_no_CB_no_INIB_CB;
/* singleton cell CB prototype declaration #_MCPP_# */
extern tCt_no_CB_no_INIB_CB  *const tCt_no_CB_no_INIB_CB_ptab[];
extern tCt_no_CB_no_INIB_CB  Ct_no_CB_no_INIB_CB;

/* celltype IDX type #_CTIX_# */
typedef ID tCt_no_CB_no_INIB_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tCt_no_CB_no_INIB_ID_BASE       (16)  /* ID Base  #_NIDB_# */
#define tCt_no_CB_no_INIB_N_CELL        (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tCt_no_CB_no_INIB_VALID_IDX(IDX) (tCt_no_CB_no_INIB_ID_BASE <= (IDX) && (IDX) < tCt_no_CB_no_INIB_ID_BASE+tCt_no_CB_no_INIB_N_CELL)


/* celll CB macro #_GCB_# */
#define tCt_no_CB_no_INIB_GET_CELLCB(idx) (tCt_no_CB_no_INIB_CB_ptab[(idx) - tCt_no_CB_no_INIB_ID_BASE])



/* var access macro #_VAM_# */
#define tCt_no_CB_no_INIB_VAR_buf(p_that)	((p_that)->buf)

#define tCt_no_CB_no_INIB_GET_buf(p_that)	((p_that)->buf)
#define tCt_no_CB_no_INIB_SET_buf(p_that,val)	((p_that)->buf=(val))

#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tCt_no_CB_no_INIB_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tCt_no_CB_no_INIB_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tCt_no_CB_no_INIB_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tCt_no_CB_no_INIB_IDX



/* var access macro (abbrev) #_VAMA_# */
#define VAR_buf              tCt_no_CB_no_INIB_VAR_buf( p_cellcb )



/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tCt_no_CB_no_INIB_N_CELL; (i)++ ){ \
       (p_cb) = tCt_no_CB_no_INIB_CB_ptab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB(p_that)	(void)(p_that);
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tCt_no_CB_no_INIB_TECSGENH */
