/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tOmit_tecsgen.h"
#include "tOmit_factory.h"


/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */

/* call port array #_CPA_# */

/* array of attr/var #_AVAI_# */
/* entry port descriptor #_EPD_# */
