/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tSCt_a_CB_no_INIB_TECSGEN_H
#define tSCt_a_CB_no_INIB_TECSGEN_H

/*
 * celltype          :  tSCt_a_CB_no_INIB
 * global name       :  tSCt_a_CB_no_INIB
 * multi-domain      :  no
 * idx_is_id(actual) :  yes(no)
 * singleton         :  yes
 * has_CB            :  yes
 * has_INIB          :  no
 * rom               :  no
 * CB initializer    :  yes
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell CB type definition #_CCTPO_# */
typedef struct tag_tSCt_a_CB_no_INIB_CB {
    int8_t*        buf;
    /* var #_VA_# */ 
    int32_t        a;
}  tSCt_a_CB_no_INIB_CB;
/* singleton cell CB prototype declaration #_SCP_# */
extern  tSCt_a_CB_no_INIB_CB  tSCt_a_CB_no_INIB_SINGLE_CELL_CB;


/* celltype IDX type #_CTIX_# */
typedef struct tag_tSCt_a_CB_no_INIB_CB *tSCt_a_CB_no_INIB_IDX;
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* celll CB macro #_GCB_# */
#define tSCt_a_CB_no_INIB_GET_CELLCB(idx) ((void *)0)



/* var access macro #_VAM_# */
#define tSCt_a_CB_no_INIB_VAR_a	(tSCt_a_CB_no_INIB_SINGLE_CELL_CB.a)
#define tSCt_a_CB_no_INIB_VAR_buf	(tSCt_a_CB_no_INIB_SINGLE_CELL_CB.buf)

#define tSCt_a_CB_no_INIB_GET_a()	(tSCt_a_CB_no_INIB_SINGLE_CELL_CB.a)
#define tSCt_a_CB_no_INIB_SET_a(val)	(tSCt_a_CB_no_INIB_SINGLE_CELL_CB.a=(val))
#define tSCt_a_CB_no_INIB_GET_buf()	(tSCt_a_CB_no_INIB_SINGLE_CELL_CB.buf)
#define tSCt_a_CB_no_INIB_SET_buf(val)	(tSCt_a_CB_no_INIB_SINGLE_CELL_CB.buf=(val))

#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tSCt_a_CB_no_INIB_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tSCt_a_CB_no_INIB_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tSCt_a_CB_no_INIB_IDX



/* var access macro (abbrev) #_VAMA_# */
#define VAR_a                tSCt_a_CB_no_INIB_VAR_a
#define VAR_buf              tSCt_a_CB_no_INIB_VAR_buf



/* CB initialize macro #_CIM_# */
#define INITIALIZE_CB()\
	tSCt_a_CB_no_INIB_SINGLE_CELL_CB.a = 5;
#define SET_CB_INIB_POINTER(i,p_that)\
	/* empty */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tSCt_a_CB_no_INIB_TECSGENH */
