name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.3'

    env:
      BUNDLE_WITH: test
      MKSPEC_GLOBAL_YAML_FNAME: ./test_data/global.yml
      MKSPEC_RESOLVED_TOP_DIR_YAML_FNAME: ./test_data/_resolved/top_dir.yml
      MKSPEC_TOP_DIR_YAML_FNAME: ./test_data/top_dir.yml
      MKSPEC_SPECIFIC_YAML_FNAME: ./test_data/specific.yml
      MKSPEC_LOG_DIR: ./test_data/logs

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: |
          gem install bundler -v 2.2.7
          bundle config with 'test'
          bundle install
          bundle exec rake

#      - name: Run the default task
#        run: bundle exec rake
